// 完整版菜单比较多，将 rank 抽离出来，在此方便维护

const home = 0, // 平台规定只有 home 路由的 rank 才能为 0 ，所以后端在返回 rank 的时候需要从非 0 开始
    detect = 1,
    chatai = 2,
    vueflow = 3,
    ganttastic = 4,
    components = 5,
    able = 6,
    table = 7,
    form = 8,
    list = 9,
    result = 10,
    error = 11,
    frame = 12,
    nested = 13,
    permission = 14,
    system = 15,
    monitor = 16,
    tabs = 17,
    about = 18,
    codemirror = 19,
    markdown = 20,
    editor = 21,
    flowchart = 22,
    formdesign = 23,
    board = 24,
    ppt = 25,
    mind = 26,
    guide = 27,
    menuoverflow = 28;

export {
    home,
    detect,
    chatai,
    vueflow,
    ganttastic,
    components,
    able,
    table,
    form,
    list,
    result,
    error,
    frame,
    nested,
    permission,
    system,
    monitor,
    tabs,
    about,
    codemirror,
    markdown,
    editor,
    flowchart,
    formdesign,
    board,
    ppt,
    mind,
    guide,
    menuoverflow
};
