set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

CREATE TABLE SYS_OPERLOG_INFO (
	LOG_ID         	VARCHAR(50) 	COMMENT '主键'  NOT NULL,
	LOG_TYPE       	CHAR(1) 		COMMENT '日志类型' DEFAULT '1',
	LOG_STATUS     	CHAR(1) 		COMMENT '操作状态  0 成功 1 失败'  NOT NULL DEFAULT '0',
	MODULE_NAME		VARCHAR(255) 	COMMENT '模块名',
	ACTION_NAME		VARCHAR(255) 	COMMENT '操作名',
	SERVICE_ID 		VARCHAR(50) 	COMMENT '服务ID',
	REMOTE_ADDR		VARCHAR(255) 	COMMENT '操作IP地址',
	USER_AGENT 		VARCHAR(1000) 	COMMENT '用户代理',
	REQUEST_URI		VARCHAR(1000) 	COMMENT '请求URI',
	METHOD_NAME     VARCHAR(10) 	COMMENT '操作方式',
	PARAMS     		TEXT 			COMMENT '操作提交的数据',
	OPER_TIME       VARCHAR(10) 	COMMENT '执行时间',
	EXCEPTION_STR  	TEXT 			COMMENT '异常信息',
	DEL_FLAG   		CHAR(1) 		COMMENT '删除标记' DEFAULT '0',
	CREATE_BY  		VARCHAR(64) 	COMMENT '创建者',
	CREATE_TIME		DATETIME 		COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	UPDATE_TIME		TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY(LOG_ID)
)
COMMENT = '操作日志表' ;

CREATE TABLE SYS_OAUTH_CLIENT (
	CLIENT_ID              		VARCHAR(100) NOT NULL,
	RESOURCES_IDS          		VARCHAR(256) NULL,
	CLIENT_SECRET          		VARCHAR(256) NULL,
	SCOPE                  		VARCHAR(256) NULL,
	AUTHORIZED_GRANT_TYPES 		VARCHAR(256) NULL,
	WEB_SERVER_REDIRECT_URI		VARCHAR(256) NULL,
	AUTHORITIES                	VARCHAR(256) NULL,
	ACCESS_TOKEN_VALIDITY  		INT(11) NULL,
	REFRESH_TOKEN_VALIDITY 		INT(11) NULL,
	ADDITION_INFORMATION   		VARCHAR(4096) NULL,
	AUTOAPPROVE                	VARCHAR(256) NULL,
	PRIMARY KEY(CLIENT_ID)
)
COMMENT = 'OAUTH2客户端资源认证表' ;

CREATE TABLE SYS_MENU_INFO (
	MENU_ID         	VARCHAR(50) 	COMMENT '主键'  NOT NULL,
	MENU_NAME       	VARCHAR(100) 	COMMENT '菜单名称'  NOT NULL,
	MENU_ROUTE_NAME     VARCHAR(100) 	COMMENT '菜单路径名称,用于多语言标识',
	MENU_TYPE       	VARCHAR(1) 		COMMENT '菜单类型 0-菜单 1-按钮'  NOT NULL DEFAULT '0',
	MENU_URL        	VARCHAR(500) 	COMMENT '后台请求URL',
	HTTP_METHOD     	VARCHAR(20) 	COMMENT '请求方式',
	MENU_PATH       	VARCHAR(300) 	COMMENT '前端URL',
	BUTTON_PERMISSION 	VARCHAR(100) 	COMMENT '按钮权限资源标识',
	MENU_COLOR      	VARCHAR(50) 	COMMENT '颜色',
	PARENT_ID  			VARCHAR(50) 	COMMENT '父资源ID'  NOT NULL,
	MENU_ICON       	VARCHAR(50) 	COMMENT '图标',
	COMPONENT_PATH  	VARCHAR(300) 	COMMENT '组件路径',
	MENU_SORT       	INT(11) 		COMMENT '排序权重',
	CREATE_TIME	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	DEL_FLAG   	VARCHAR(1) COMMENT '是否删除 1-删除，0-未删除' DEFAULT '0',
	APP_ID 		VARCHAR(50) COMMENT '租户ID',
	AUTH_FLAG 		CHAR(1) COMMENT '权限标识:0-不需要权限;1-需要权限',
	HIDE_FLAG 		CHAR(1) COMMENT '隐藏菜单：0-否;1-是',
	ALIVE_FLAG 		CHAR(1) COMMENT '缓存组件：0-否;1-是',
	PRIMARY KEY(MENU_ID)
)
COMMENT = '菜单表' ;

CREATE TABLE SYS_ROLE_MENU_REL (
	ROLE_ID    	VARCHAR(50) COMMENT '主键'  NOT NULL,
	MENU_ID		VARCHAR(50) COMMENT '主键'  NOT NULL,
	PRIMARY KEY(ROLE_ID, MENU_ID)
)
COMMENT = '角色菜单关联表' ;

CREATE TABLE SYS_ROLE_INFO (
	ROLE_ID    	VARCHAR(50) 	COMMENT '主键'  NOT NULL,
	ROLE_CODE  	VARCHAR(50) 	COMMENT '角色CODE用于SPRINGSECURITY角色标识码'  NOT NULL,
	ROLE_NAME  	VARCHAR(128) 	COMMENT '角色名称'  NOT NULL,
	APP_ID 		VARCHAR(50) 	COMMENT '租户ID',
	CREATE_TIME	TIMESTAMP 		COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	DEL_FLAG   	CHAR(1) COMMENT '是否删除 1-删除，0-未删除' DEFAULT '0',
	PRIMARY KEY(ROLE_ID)
)
COMMENT = '角色表' ;

CREATE TABLE SYS_ROLE_USER_REL (
	USER_ID	VARCHAR(50) COMMENT '主键'  NOT NULL,
	ROLE_ID	VARCHAR(50) COMMENT '主键'  NOT NULL,
	PRIMARY KEY(USER_ID,ROLE_ID)
)
COMMENT = '用户角色关联表' ;

CREATE TABLE SYS_USER_INFO (
	USER_ID      	VARCHAR(50)				COMMENT '主键ID'  NOT NULL,
	LOGIN_NAME		VARCHAR(100)	binary	COMMENT '登录名'  NOT NULL,
	USER_NAME     	VARCHAR(200) 			COMMENT '用户名'  NOT NULL,
	LOGIN_PWD     	VARCHAR(200) 			COMMENT '密码'  NOT NULL,
	USER_EMAIL      VARCHAR(200) 			COMMENT '邮箱',
	USER_MOB_TEL   	VARCHAR(30) 			COMMENT '手机号码'  NOT NULL,
	DEL_FLAG     	CHAR(1) 				COMMENT '是否删除 0-未删除 1-删除' DEFAULT '0',
	BRANCH_NO 		VARCHAR(50) NOT NULL 	COMMENT '机构编号',
    CRYPT_PWD 		VARCHAR(200) NOT NULL 	COMMENT '内部加密密码',
	APP_ID 			VARCHAR(50)     COMMENT '租户ID'  NULL,
	LOGIN_TIME  	TIMESTAMP 		COMMENT '登录时间' NULL DEFAULT NULL,
	CREATE_TIME  	TIMESTAMP 		COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY(USER_ID)
)
COMMENT = '用户表' ;

CREATE TABLE SYS_ZUUL_ROUTE (
	ROUTE_ID                VARCHAR(50) 	COMMENT 'ROUTER ID'  NOT NULL,
	ROUTE_PATH              VARCHAR(255) 	COMMENT '路由路径'  NOT NULL,
	SERVICE_ID           	VARCHAR(255) 	COMMENT '服务名称'  NOT NULL,
	URL_PROXY               VARCHAR(255) 	COMMENT 'URL代理',
	STRIP_PREFIX         	CHAR(1) 		COMMENT '转发去掉前缀' DEFAULT '1',
	RETRYABLE_FLAG          CHAR(1) 		COMMENT '是否重试' DEFAULT '1',
	ENABLED_FLAG            CHAR(1) 		COMMENT '是否启用' DEFAULT '1',
	HEADERS_LIST			VARCHAR(255) 	COMMENT '敏感请求头',
	CREATE_TIME          	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	UPDATE_TIME          	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	DEL_FLAG             	CHAR(1) COMMENT '删除标识（0-正常,1-删除）' DEFAULT '0',
	PRIMARY KEY(ROUTE_ID)
)
COMMENT = '动态路由配置表' ;

CREATE TABLE SYS_ANNO_TYPE_INFO (
  TYPE_ID 		VARCHAR(50) NOT NULL 	COMMENT '主键ID',
  APP_ID 		VARCHAR(50) NOT NULL 	COMMENT '租户ID',
  TYPE_NAME 	VARCHAR(200) NOT NULL 	COMMENT '类型名称',
  CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
  MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  TYPE_RMK 		VARCHAR(500) DEFAULT NULL COMMENT '类型描述',
  PRIMARY KEY (TYPE_ID)
) 
COMMENT='公告类型信息表';

CREATE TABLE SYS_ANNO_INFO (
  ANNO_ID 		VARCHAR(50) NOT NULL 	COMMENT '公告ID',
  ANNO_LEVEL 	CHAR(1) NOT NULL 		COMMENT '公告等级',
  IS_VALID 		TINYINT(1) NOT NULL 	COMMENT '是否有效',
  ANNO_TITLE 	VARCHAR(255) NOT NULL 	COMMENT '公告标题',
  ANNO_CONTENT 	MEDIUMTEXT 					COMMENT '公告内容',
  LOGIN_NAME 	VARCHAR(50) NOT NULL 	COMMENT '登录名',
  TYPE_ID 		VARCHAR(50) NOT NULL 	COMMENT '公告类型ID',
  START_TIME 	DATETIME DEFAULT NULL 	COMMENT '公告有效期：生效时间',
  END_TIME 		DATETIME DEFAULT NULL 	COMMENT '公告有效期：结束时间',
  APP_ID 		VARCHAR(50) NOT NULL 	COMMENT '租户ID',
  CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
  MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (ANNO_ID)
) 
COMMENT='公告信息表';

CREATE TABLE SYS_ANNO_ATTACH_INFO (
  ATT_ID VARCHAR(50) NOT NULL 		COMMENT '附件ID',
  ANNO_ID VARCHAR(50) NOT NULL 		COMMENT '公告ID',
  APP_ID VARCHAR(50) NOT NULL 		COMMENT '租户ID',
  ATT_NAME VARCHAR(200) NOT NULL 	COMMENT '附件名称',
  ATT_CONTENT MEDIUMBLOB NOT NULL 	COMMENT '附件内容',
  PRIMARY KEY (ATT_ID)
) 
COMMENT='公告附件信息表';

CREATE TABLE SYS_ANNO_USER_OPER (
  ANNO_ID VARCHAR(50) NOT NULL 		COMMENT '公告ID',
  USER_ID VARCHAR(50) NOT NULL 		COMMENT '用户ID',
  READ_FLAG VARCHAR(1) NOT NULL		COMMENT '0-未读, 1-已读',
  DELE_FLAG VARCHAR(1) NOT NULL		COMMENT '0-未删除, 1-已删除',
  PRIMARY KEY (ANNO_ID, USER_ID)
) 
COMMENT='公告用户状态表';

CREATE TABLE SYS_USER_GROUP_REL  (
  GROUP_ID  VARCHAR(50) NOT NULL COMMENT '用户组ID',
  USER_ID  VARCHAR(50) NOT NULL COMMENT '用户ID',
  PRIMARY KEY (GROUP_ID, USER_ID)
) 
COMMENT='用户组关系表';

CREATE TABLE SYS_USER_GROUP_INFO  (
  GROUP_ID VARCHAR(50) NOT NULL COMMENT '用户组ID',
  GROUP_NAME VARCHAR(300) DEFAULT NULL COMMENT '用户组名称',
  GROUP_RMK VARCHAR(500) DEFAULT NULL COMMENT '用户组描述',
  APP_ID VARCHAR(50) COMMENT '租户ID',
  PRIMARY KEY( GROUP_ID )
) 
COMMENT='用户组';

CREATE TABLE SYS_GROUP_BRANCH_REL  (
  GROUP_ID  VARCHAR(50) NOT NULL COMMENT '用户组ID',
  BRANCH_NO  VARCHAR(50) NOT NULL COMMENT '机构号',
  PRIMARY KEY (GROUP_ID, BRANCH_NO)
) 
COMMENT='用户机构关系表';

CREATE TABLE `SYS_DBLINK_INFO` (
  `DBLINK_ID` VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_BIN NOT NULL COMMENT '数据源ID',
  `DBLINK_NAME` VARCHAR(255) CHARACTER SET UTF8 COLLATE UTF8_BIN NOT NULL COMMENT '数据源英文名',
  `DBLINK_RMK` VARCHAR(500) CHARACTER SET UTF8 COLLATE UTF8_BIN DEFAULT NULL COMMENT '数据源描述',
  `DBLINK_TYPE` CHAR(1) CHARACTER SET UTF8 COLLATE UTF8_BIN NOT NULL COMMENT '数据源类型',
  `DBLINK_DRIVER` VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_BIN NOT NULL COMMENT '驱动',
  `DBLINK_URL` VARCHAR(200) CHARACTER SET UTF8 COLLATE UTF8_BIN NOT NULL COMMENT 'URL',
  `DBLINK_USER` VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_BIN NOT NULL COMMENT '用户',
  `DBLINK_PWD` VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_BIN NOT NULL COMMENT '密码',
  `POOL_TYPE` CHAR(1) CHARACTER SET UTF8 COLLATE UTF8_BIN DEFAULT NULL COMMENT '连接池类型',
  `CREATE_TIME` TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `INITIAL_SIZE` INT(4) DEFAULT NULL COMMENT '初始化时物理连接个数',
  `MAX_ACTIVE` INT(11) DEFAULT NULL COMMENT '最大连接池数量',
  `MIN_IDLE` INT(11) DEFAULT NULL COMMENT '最小连接池数量',
  `CACHE_FLAG` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT '缓存标识',
  `MAX_PS_CATCH` INT(11) DEFAULT NULL COMMENT '最大缓存数量',
  `VALIDATION_QUERY` VARCHAR(100) COLLATE UTF8_BIN DEFAULT NULL COMMENT '参数SQL',
  `MAX_WAIT` INT(11) DEFAULT NULL COMMENT '获取连接等待超时时间',
  `TEST_ON_BORROW` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT '取连接时是否检查连接有效性',
  `TEST_ON_RETURN` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT '归还连接时是否检查连接有效性',
  `TEST_WHILE_IDLE` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT '获取连接时是否检查连接有效性',
  `TIME_BTN_EVICTION_RUNS_MILLIS` INT(11) DEFAULT NULL COMMENT '检测周期',
  `MIN_EVICTABLE_IDLE_TIME_MILLIS` INT(11) DEFAULT NULL COMMENT '最大空闲时间',
  `POOL_PREPARED_STATEMENTS` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT 'PSCACHE打开标识',
  `MAX_PS_CATCH_SIZE` INT(11) DEFAULT NULL COMMENT 'PSCATCH缓存最大数',
  `REMOVE_ABANDONED` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT '泄漏检查标识',
  `REMOVE_ABANDONED_TIMEOUT` INT(11) DEFAULT NULL COMMENT '超时时间',
  `FILTERS` VARCHAR(100) COLLATE UTF8_BIN DEFAULT NULL COMMENT '扩展插件',
  PRIMARY KEY (`DBLINK_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN COMMENT='数据源信息表';


CREATE TABLE `NOTICE_MAIL_SEND_LOG` (
  `LOG_ID` VARCHAR(50)  NOT NULL COMMENT '日志ID',
  `LOG_STATE` CHAR(1)  NOT NULL COMMENT '发送状态',
  `LOGIN_NAME` VARCHAR(50)  NOT NULL COMMENT '用户登录名',
  `SRV_ID` VARCHAR(50)  NOT NULL COMMENT '服务器ID',
  `TEMP_ID` VARCHAR(50)  NOT NULL COMMENT '模板ID',
  `ERROR_STR` VARCHAR(2000)  DEFAULT NULL COMMENT '异常信息',
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
  PRIMARY KEY (`LOG_ID`)
)  COMMENT='邮件日志信息表';

CREATE TABLE `NOTICE_MAIL_SRV_INFO` (
  `SRV_ID` VARCHAR(50)  NOT NULL COMMENT '服务器标识',
  `SRV_NAME` VARCHAR(200)  NOT NULL COMMENT '服务器名称',
  `SRV_RMK` VARCHAR(300)  DEFAULT NULL COMMENT '服务器描述',
  `SRV_URL` VARCHAR(200)  NOT NULL COMMENT '服务器地址',
  `SRV_PORT` int  NOT NULL COMMENT '服务器端口',
  `LOGIN_NAME` VARCHAR(50)  COMMENT '用户名',
  `LOGIN_PWD` VARCHAR(50)  COMMENT '密码',
  `DEFAULT_FROM` VARCHAR(100)  NOT NULL COMMENT '邮箱地址',
  `SHOW_NAME` VARCHAR(100)  COMMENT '显示名称',
  `SSL_FLAG` VARCHAR(1)  NOT NULL COMMENT '是否启用SSL',
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `APP_ID` varchar(50) DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`SRV_ID`)
)  COMMENT='邮件服务器信息表';

CREATE TABLE `NOTICE_MAIL_TEMP_INFO` (
  `TEMP_ID` VARCHAR(50)  NOT NULL COMMENT '模板ID',
  `TEMP_NAME` VARCHAR(200)  NOT NULL COMMENT '模板名称',
  `TEMP_CONTENT` longtext  DEFAULT NULL COMMENT '模板内容',
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `APP_ID` varchar(50) DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`TEMP_ID`)
)  COMMENT='邮件模板';

CREATE TABLE `SYS_TASK_INFO` (
  `TASK_ID` VARCHAR(50) COLLATE UTF8_BIN NOT NULL COMMENT '任务ID',
  `TASK_NAME` VARCHAR(255) COLLATE UTF8_BIN NOT NULL COMMENT '任务名称',
  `EXEC_CLASS` VARCHAR(100) COLLATE UTF8_BIN NOT NULL COMMENT '执行类',
  `EXEC_METHOD` VARCHAR(50) COLLATE UTF8_BIN NOT NULL COMMENT '执行函数',
  `TRIGGER_ID` VARCHAR(50) COLLATE UTF8_BIN NOT NULL COMMENT '调度策略ID',
  `START_TIME` VARCHAR(32) COLLATE UTF8_BIN NOT NULL COMMENT '开始时间',
  `END_TIME` VARCHAR(32) COLLATE UTF8_BIN NOT NULL COMMENT '结束时间',
  `TASK_STATUS` CHAR(1) COLLATE UTF8_BIN NOT NULL COMMENT '任务状态',
  `LOGIN_NAME` VARCHAR(50) COLLATE UTF8_BIN NOT NULL COMMENT '创建任务用户登录名',
  `TASK_RMK` VARCHAR(500) COLLATE UTF8_BIN DEFAULT NULL COMMENT '任务描述',
  `EXT_ATTR1` VARCHAR(100) COLLATE UTF8_BIN DEFAULT NULL COMMENT '拓展属性1',
  `EXT_ATTR2` VARCHAR(100) COLLATE UTF8_BIN DEFAULT NULL COMMENT '拓展属性2',
  `CREATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `DEL_FLAG` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT '删除标识',
  PRIMARY KEY (`TASK_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN COMMENT='调度任务信息表';

CREATE TABLE `SYS_TASK_LOG_INFO` (
  `LOG_ID` VARCHAR(50) COLLATE UTF8_BIN NOT NULL COMMENT '日志ID',
  `TASK_ID` VARCHAR(50) COLLATE UTF8_BIN DEFAULT NULL COMMENT '任务ID',
  `TASK_NAME` VARCHAR(255) COLLATE UTF8_BIN DEFAULT NULL COMMENT '任务名称',
  `EXEC_STATUS` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT '执行状态',
  `CREATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '执行时间',
  `LOG_CONTENT` VARCHAR(2000) COLLATE UTF8_BIN DEFAULT NULL COMMENT '日志内容',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN COMMENT='调度日志信息表';

CREATE TABLE `SYS_TASK_TRIGGER_INFO` (
  `TRIGGER_ID` VARCHAR(50) COLLATE UTF8_BIN NOT NULL COMMENT '策略ID',
  `TRIGGER_NAME` VARCHAR(255) COLLATE UTF8_BIN NOT NULL COMMENT '策略名称',
  `TRIGGER_TYPE` CHAR(1) COLLATE UTF8_BIN NOT NULL COMMENT '策略类型',
  `CRON_EXPRESSION` VARCHAR(100) COLLATE UTF8_BIN DEFAULT NULL COMMENT 'CRON表达式',
  `REPEAT_COUNT` INT(11) DEFAULT NULL COMMENT '调度次数',
  `REPEAT_INTERVAL` INT(11) DEFAULT NULL COMMENT '调度间隔',
  `START_DELAY` INT(11) DEFAULT NULL COMMENT '调度延迟时间',
  `CREATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `DEL_FLAG` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL COMMENT '删除标识',
  PRIMARY KEY (`TRIGGER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN COMMENT='调度策略信息表';

CREATE TABLE `SYS_FILE_SERVER_INFO` (
  `FILE_SERVER_ID` VARCHAR(50) COLLATE UTF8_BIN NOT NULL COMMENT '文件服务器ID',
  `FILE_SERVER_NAME` VARCHAR(255) COLLATE UTF8_BIN NOT NULL COMMENT '名称',
  `FILE_SERVER_RMK` VARCHAR(500) COLLATE UTF8_BIN DEFAULT NULL COMMENT '描述',
  `FILE_SERVER_TYPE` CHAR(1) COLLATE UTF8_BIN NOT NULL COMMENT '服务器类型',
  `FILE_SERVER_IP` VARCHAR(50) COLLATE UTF8_BIN DEFAULT NULL COMMENT 'IP地址',
  `FILE_SERVER_PORT` VARCHAR(20) COLLATE UTF8_BIN DEFAULT NULL COMMENT '端口号',
  `FILE_SERVER_USER` VARCHAR(50) COLLATE UTF8_BIN DEFAULT NULL COMMENT '用户',
  `FILE_SERVER_PWD` VARCHAR(50) COLLATE UTF8_BIN DEFAULT NULL COMMENT '密码',
  `PROTOCOL` VARCHAR(100) COLLATE UTF8_BIN NOT NULL COMMENT '协议',
  `FILE_SERVER_PATH` VARCHAR(500) COLLATE UTF8_BIN DEFAULT NULL COMMENT '目录',
  `CREATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `DEL_FLAG` CHAR(1) COLLATE UTF8_BIN DEFAULT NULL,
  PRIMARY KEY (`FILE_SERVER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN COMMENT='文件服务器信息表';


CREATE TABLE SYS_BRANCH_INFO  (
   BRANCH_NO  VARCHAR(200) NOT NULL COMMENT '机构号',
   BRANCH_NAME  VARCHAR(255) DEFAULT NULL COMMENT '机构名称',
   BRANCH_SHORT_NAME  VARCHAR(255) DEFAULT NULL COMMENT '机构简称',
   BRANCH_TYPE  CHAR(1) DEFAULT NULL COMMENT '机构类型',
   PARENT_BRANCH_NO  VARCHAR(100) DEFAULT NULL COMMENT '父级机构编号',
   ET_FLAG  CHAR(1) DEFAULT NULL COMMENT 'ETL同步',
   VIR_FLAG  CHAR(1) DEFAULT NULL COMMENT '是否是虚拟机构',
  PRIMARY KEY ( BRANCH_NO )
)
COMMENT='机构信息表';

CREATE TABLE SYS_HELP_FILE_INFO (
  HELP_FILE_ID VARCHAR(50) NOT NULL COMMENT '帮助文档ID',
  HELP_FILE_NAME VARCHAR(300) DEFAULT NULL COMMENT '帮助文档名称',
  HELP_FILE_SIZE bigint DEFAULT 0 COMMENT '帮助文档大小',
  HELP_FILE_TYPE VARCHAR(10) DEFAULT NULL COMMENT '帮助文档类型',
  HELP_FILE_CONTENT LongBlob DEFAULT NULL COMMENT '帮助文档文件',
  PRIMARY KEY (HELP_FILE_ID)
) 
COMMENT='帮助文档信息表';

CREATE TABLE SYS_MIGRATE_INFO (
  MIG_ID VARCHAR(50) NOT NULL COMMENT 'ID',
  MIG_TAB_NAME VARCHAR(50) DEFAULT NULL COMMENT '表英文名',
  MIG_TAB_CNAME VARCHAR(200) DEFAULT NULL COMMENT '表中文名',
  MIG_TYPE CHAR(1) DEFAULT NULL COMMENT '表类型',
  MIG_COL_ID VARCHAR(50) DEFAULT NULL COMMENT '主键字段',
  MIG_COL_NAME VARCHAR(200) DEFAULT NULL COMMENT '主键字段中文名',
  PARENT_MIG_ID VARCHAR(50) DEFAULT NULL COMMENT '父级ID',
  MIG_REL_ID VARCHAR(50) DEFAULT NULL COMMENT '关联表关联字段',
  MIG_REL_NAME VARCHAR(200) DEFAULT NULL COMMENT '关联表-关联字段名称',
  MIG_REL_TYPE CHAR(1) DEFAULT NULL COMMENT '关联表-关联字段解析类型',
  MIG_REL_VALUE VARCHAR(50) DEFAULT NULL COMMENT '关联表-关联字段提取值',
  MIG_END_SIGN VARCHAR(50) DEFAULT NULL COMMENT '自关联结束标识',
  MIG_CONVER_TYPE CHAR(1) DEFAULT NULL,
  PRIMARY KEY (MIG_ID)
) 
COMMENT='导入导出信息配置表';

CREATE TABLE SYS_MESSAGE_INFO (
  MESSAGE_ID VARCHAR(50) NOT NULL COMMENT '消息ID',
  MESSAGE_TYPE CHAR(1) DEFAULT NULL COMMENT '消息类型:1-提醒;2-通知',
  MESSAGE_STATUS CHAR(1) DEFAULT NULL COMMENT '消息状态:0-未读;1-已读',
  MESSAGE_TITLE VARCHAR(50) DEFAULT NULL COMMENT '消息标题',
  MESSAGE_CONTENT VARCHAR(500) DEFAULT NULL COMMENT '消息内容',
  MESSAGE_REV_USER VARCHAR(50) DEFAULT NULL COMMENT '消息接收用户',
  DEL_FLAG   CHAR(1) 		COMMENT '删除标记' DEFAULT '0',
  APP_ID     	VARCHAR(50) NULL COMMENT '租户ID',
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY_TIME TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (MESSAGE_ID)
)
COMMENT='用户消息信息表';

CREATE TABLE SYS_STATISTICAL_STRATEGY (
  STRATEGY_ID VARCHAR(50) NOT NULL COMMENT '策略ID',
  SERVICE_URL VARCHAR(200) DEFAULT NULL COMMENT '服务地址',
  FUNCTION_NAME VARCHAR(50)  DEFAULT NULL COMMENT '功能名称',
  REPEAT_FLAG CHAR(1) DEFAULT NULL COMMENT '是否重复计数,0-否;1-是',
  CONFIG_STATUS CHAR(1) DEFAULT NULL COMMENT '策略状态,0-停用;1-启用',
  DEL_FLAG   CHAR(1) 		COMMENT '删除标记' DEFAULT '0',
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY_TIME TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (STRATEGY_ID)
)
COMMENT='统计策略表';

CREATE TABLE SYS_STATISTICAL_INFO (
  STATISTICAL_ID VARCHAR(50) NOT NULL COMMENT '统计ID',
  STRATEGY_ID VARCHAR(50) NOT NULL COMMENT '统计策略ID',
  REQUEST_URL VARCHAR(200) DEFAULT NULL COMMENT '请求地址',
  REQUEST_USER_ID VARCHAR(200) DEFAULT NULL COMMENT '请求用户ID',
  REQUEST_HOST VARCHAR(50)  DEFAULT NULL COMMENT '请求主机IP',
  USER_AGENT VARCHAR(500)  DEFAULT NULL COMMENT '用户代理',
  REQUEST_METHOD VARCHAR(20)  DEFAULT NULL COMMENT '请求方式',
  REQUEST_TIME VARCHAR(20)  DEFAULT NULL COMMENT '请求时间',
  RESPONSE_STATUS VARCHAR(10) DEFAULT NULL COMMENT '响应状态码',
  RESPONSE_DATA_SIZE INT(11) DEFAULT NULL COMMENT '响应数据大小',
  PRIMARY KEY (STATISTICAL_ID)
)
COMMENT='统计信息表';
CREATE TABLE SYS_PARAM_INFO ( 
    PARAM_ID   	VARCHAR(50) NOT NULL COMMENT '参数ID',
    PARAM_NAME 	VARCHAR(200) NULL COMMENT '参数名称',
    PARAM_VALUE	VARCHAR(200) NULL COMMENT '参数值',
    PARAM_RMK  	VARCHAR(300) NULL COMMENT '参数描述',
    APP_ID     	VARCHAR(50) NULL COMMENT '租户ID',
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  	MODIFY_TIME TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY(PARAM_ID)
)
COMMENT='参数信息表';

CREATE TABLE `SYS_APP_INFO` (
  `APP_ID` VARCHAR(50) NOT NULL COMMENT '租户ID',
  `APP_NAME` VARCHAR(200) DEFAULT NULL COMMENT '租户名称',
  `APP_ORDER` INT(11) DEFAULT 0 COMMENT '租户排序',
  `APP_LOGO` VARCHAR(300) DEFAULT NULL COMMENT '租户LOGO路径',
  `BROWSER_TITLE` VARCHAR(100) DEFAULT NULL COMMENT '浏览器标题',
  `APP_URL` VARCHAR(500) DEFAULT NULL COMMENT '租户地址',
  `APP_RMK` VARCHAR(100) DEFAULT NULL COMMENT '租户描述',
  `APP_REL` VARCHAR(50) DEFAULT NULL COMMENT '关联租户',
  `APP_STATE` VARCHAR(1) DEFAULT NULL COMMENT '租户状态',
  PRIMARY KEY (`APP_ID`)
)
COMMENT='租户信息表';

CREATE TABLE `SYS_USER_APP_REL` (
  `USER_ID` VARCHAR(50) NOT NULL COMMENT '用户ID',
  `APP_ID` VARCHAR(50) NOT NULL COMMENT '租户ID',
 	PRIMARY KEY(USER_ID, APP_ID)
) 
COMMENT='租户用户权限表';

CREATE TABLE `SYS_COLLECT_INFO` (
  `COLLECT_ID` VARCHAR(50) NOT NULL COMMENT '收藏项ID',
  `COLLECT_NAME` VARCHAR(200) NOT NULL COMMENT '收藏项名称',
  `COLLECT_OBJ` VARCHAR(50) NOT NULL COMMENT '收藏项目标ID',
  `COLLECT_TYPE` INT(2) NOT NULL COMMENT '收藏项目标类型',
  `APP_ID` VARCHAR(50) NOT NULL COMMENT '租户ID',
  `USER_ID` VARCHAR(50) NOT NULL COMMENT '用户ID',
  `PARENT_ID` VARCHAR(50) NOT NULL COMMENT '父ID',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `COLLECT_RMK` VARCHAR(500) DEFAULT NULL COMMENT '收藏项描述',
  `COLLECT_ICON` VARCHAR(100) NOT NULL,
  `COLLECT_URL` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`COLLECT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='收藏信息表';

CREATE TABLE `SYS_MENU_TMP` (
  `MENU_ID` VARCHAR(50)  NOT NULL COMMENT '主键',
  `MENU_NAME` VARCHAR(64)  NOT NULL COMMENT '菜单名称',
  `MENU_ROUTE_NAME` VARCHAR(64) DEFAULT NULL COMMENT '菜单路径名称,用于多语言标识',
  `MENU_TYPE` CHAR(1) NOT NULL DEFAULT '0' COMMENT '菜单类型 0-菜单 1-按钮',
  `MENU_URL` VARCHAR(255)  DEFAULT NULL COMMENT '后台请求URL',
  `HTTP_METHOD` VARCHAR(20) DEFAULT NULL COMMENT '请求方式',
  `MENU_PATH` VARCHAR(128) DEFAULT NULL COMMENT '前端URL',
  `BUTTON_PERMISSION` VARCHAR(32) DEFAULT NULL COMMENT '按钮权限资源标识',
  `MENU_COLOR` VARCHAR(64) DEFAULT NULL COMMENT '颜色',
  `PARENT_ID` VARCHAR(50) NOT NULL COMMENT '父资源ID',
  `MENU_ICON` VARCHAR(32)  DEFAULT NULL COMMENT '图标',
  `COMPONENT_PATH` VARCHAR(128) DEFAULT NULL COMMENT '组件路径',
  `MENU_SORT` INT(11) DEFAULT 0 COMMENT '排序权重',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `DEL_FLAG` CHAR(1)  DEFAULT '0' COMMENT '是否删除 1-删除，0-未删除',
  `APP_ID` VARCHAR(50) DEFAULT NULL COMMENT '租户ID',
  `APP_FLAG` CHAR(1) DEFAULT '0' COMMENT '管理端标识 1-管理端，0-业务端',
  PRIMARY KEY (`MENU_ID`)
) COMMENT='菜单模板表';


CREATE TABLE NOTICE_SMS_SEND_LOG
(
	LOG_ID VARCHAR(50) NOT NULL COMMENT '主键',
	SRV_ID VARCHAR(50) NOT NULL COMMENT '服务器ID',
	SMS_SEND_TIME VARCHAR(50) NOT NULL COMMENT '发送时间',
	SMS_SEND_USER VARCHAR(50) NOT NULL COMMENT '发送用户',
	SMS_RECEIVE_USER VARCHAR(2000) NOT NULL COMMENT '所有接收者',
	SEND_CONTENT VARCHAR(500) COMMENT '发送内容',
	SEND_STATUS VARCHAR(6) COMMENT '发送状态',
	PRIMARY KEY (LOG_ID)
) COMMENT='短信服务器发送日志表 ';

CREATE TABLE NOTICE_SMS_SRV_INFO
(
	SRV_ID VARCHAR(50) NOT NULL COMMENT '主键',
	SRV_NAME VARCHAR(200) NOT NULL COMMENT '服务器名称',
	SRV_SMS_PROGRAM VARCHAR(200) NOT NULL COMMENT '短信发送接口实现类',
	SRV_RMK VARCHAR(1000) COMMENT '服务器描述',
	SRV_EXTEND_FIELD VARCHAR(1000) COMMENT '服务器扩展属性',
	APP_ID varchar(50) DEFAULT NULL COMMENT '租户ID',
	PRIMARY KEY (SRV_ID)
) COMMENT='短信服务器信息表 ';

CREATE TABLE NOTICE_SMS_TEMP_INFO
(
    TEMP_ID VARCHAR(50) NOT NULL COMMENT '主键',
    EXT_ATTR1 VARCHAR(100) COMMENT '扩展属性1',
    EXT_ATTR2 VARCHAR(200) COMMENT '扩展属性2',
    EXT_ATTR3 VARCHAR(1000) COMMENT '扩展属性3',
    TEMP_HTML longtext COMMENT '短信模板内容',
    TEMP_NAME VARCHAR(200) COMMENT '短信模板名称',
    TEMP_RMK VARCHAR(300) COMMENT '短信模板描述',
    TEMP_USER VARCHAR(50) COMMENT '创建用户',
    APP_ID varchar(50) DEFAULT NULL COMMENT '租户ID',
    PRIMARY KEY (TEMP_ID)
)COMMENT='短信模板信息表 ';

CREATE TABLE NOTICE_SYSTEM_MESSAGE
(
	MSG_ID VARCHAR(50) NOT NULL COMMENT '主键',
	RECEIVE_USER VARCHAR(50) NOT NULL COMMENT '消息接收者',
	SEND_USER VARCHAR(50) NOT NULL COMMENT '消息发送者',
	SEND_TIME VARCHAR(50) NOT NULL COMMENT '消息发送时间',
	READ_FLAG VARCHAR(6) NOT NULL COMMENT '消息是否已读状态',
	MSG_CONTENT VARCHAR(2000) COMMENT '消息内容',
	MSG_THEME VARCHAR(200) COMMENT '消息主题',
	PRIMARY KEY (MSG_ID)
)COMMENT='系统消息表 ';

CREATE TABLE KNOW_KNOWLEDGE_ATTACH_INFO
(
	ATT_ID VARCHAR(50) NOT NULL COMMENT '附件id',
	KNOWLEDGE_ID VARCHAR(50) NOT NULL COMMENT '知识库id',
	APP_ID VARCHAR(50) NOT NULL COMMENT '租户id',
	ATT_NAME VARCHAR(200) NOT NULL COMMENT '附件名称',
	ATT_CONTENT mediumblob NOT NULL COMMENT '附件内容',
	CREATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY_TIME timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (ATT_ID)
) COMMENT='知识库附件信息表';

CREATE TABLE KNOW_KNOWLEDGE_DIR_INFO
(
	DIR_ID VARCHAR(50) NOT NULL COMMENT '分类ID',
	DIR_NAME VARCHAR(200) COMMENT '分类名称',
	PARENT_ID VARCHAR(50) COMMENT '父ID',
	DIR_RMK VARCHAR(300) COMMENT '分类描述',
	APP_ID varchar(50) DEFAULT NULL COMMENT '租户ID',
	CREATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY_TIME timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	DIR_ORDER INT COMMENT '排序',
	PRIMARY KEY (DIR_ID)
)COMMENT='知识分类表';

CREATE TABLE `KNOW_KNOWLEDGE_INFO` (
  `KNOWLEDGE_ID` varchar(50) NOT NULL COMMENT '知识ID',
  `KNOWLEDGE_TITLE` varchar(200) DEFAULT NULL COMMENT '知识标题',
  `KNOWLEDGE_RMK` varchar(300) DEFAULT NULL COMMENT '知识描述',
  `KEY_WORDS` varchar(500) DEFAULT NULL COMMENT '关键词',
  `KNOWLEDGE_STATUS` varchar(1) DEFAULT NULL COMMENT '知识状态',
  `CREATE_USER` varchar(50) DEFAULT NULL COMMENT '创建用户',
  `MODIFY_USER` varchar(50) DEFAULT NULL COMMENT '修改用户',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `MODIFY_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `KNOWLEDGE_CONTENT` MEDIUMTEXT NOT NULL COMMENT '知识内容',
  `DIR_ID` varchar(50) DEFAULT NULL COMMENT '分类ID',
  `APP_ID` varchar(50) DEFAULT NULL COMMENT '租户ID',
  `KNOWLEDGE_CONTENT_EDIT_TYPE` varchar(1) DEFAULT NULL COMMENT '知识内容类型',
  PRIMARY KEY (`KNOWLEDGE_ID`)
) COMMENT='知识库表';

CREATE TABLE SYS_USER_COMMENT_INFO(
	COMMENT_ID	VARCHAR(50) NOT NULL COMMENT '评论id',
	COMMENT_CONTENT TEXT COMMENT '评论内容',
	COMMENT_OBJID VARCHAR(50) NOT NULL COMMENT '评论对象ID',
	CREATE_USER VARCHAR(50) NOT NULL COMMENT '创建用户',
	APP_ID 		VARCHAR(50) NOT NULL 	COMMENT '租户ID',
	CREATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	PRIMARY KEY (COMMENT_ID)
) COMMENT='用户评论信息表';

CREATE TABLE SYS_WORKFLOW_TYPE_INFO(
    TYPE_ID VARCHAR(50) NOT NULL   		COMMENT '工作流类型ID' ,
    TYPE_NAME VARCHAR(100)    			COMMENT '工作流类型名称' ,
    TYPE_RMK VARCHAR(300)    			COMMENT '工作流类型描述' ,
	TYPE_ORDER INT						COMMENT '工作流类型排序' ,
    APP_ID 		VARCHAR(50) NOT NULL 	COMMENT '租户ID',
	CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (TYPE_ID)
) COMMENT = '工作流类型信息 ';

CREATE TABLE SYS_WORKFLOW_INFO(
    WORKFLOW_ID VARCHAR(50) NOT NULL   	COMMENT '工作流ID' ,
	WORKFLOW_CODE VARCHAR(100) NOT NULL COMMENT '工作流标识' ,
    WORKFLOW_NAME VARCHAR(100)    		COMMENT '工作流名称' ,
	VERSION_NUM VARCHAR(10)				COMMENT '工作流版本' ,
	VERSION_MAX	VARCHAR(1)				COMMENT '最大版本标志' ,
    WORKFLOW_RMK VARCHAR(300)    		COMMENT '工作流描述' ,
	WORKFLOW_LEVEL INT		    		COMMENT '工作流级别' ,
	TYPE_ID VARCHAR(50) NOT NULL   		COMMENT '工作流类型ID' ,
    WF_ID VARCHAR(100)    				COMMENT '流程平台ID' ,
	DETAIL_URL	VARCHAR(1000)			COMMENT '详情获取地址' ,	
	FINISH_SERVICE	VARCHAR(1000)		COMMENT '结束回调服务' ,	
	APP_ID 		VARCHAR(50) NOT NULL 	COMMENT '租户ID',
	CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (WORKFLOW_ID)
) COMMENT = '工作流定义信息 ';

CREATE TABLE SYS_WORKFLOW_NODE_INFO(
    NODE_ID VARCHAR(50) NOT NULL   	COMMENT '节点ID' ,
    NODE_NAME VARCHAR(100)    		COMMENT '节点名称' ,
    PARENT_IDS VARCHAR(1000)    	COMMENT '多上级节点ID' ,
	NODE_LEVEL int					COMMENT '节点层级',
    WORKFLOW_ID VARCHAR(50)    		COMMENT '工作流ID' ,
    NODE_RMK VARCHAR(300)    		COMMENT '节点说明' ,
    AGREE_NUM INT    				COMMENT '通过人数 0-所有人通过、N-n个人通过' ,
    DISAGREE_NUM INT    			COMMENT '不通过人数 0-所有人不通过、N-n个人不通过' ,
    CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (NODE_ID)
) COMMENT = '工作流节点信息 ';

CREATE TABLE SYS_WORKFLOW_NODE_AUTH(
    AUTH_ID VARCHAR(50) NOT NULL   	COMMENT '权限ID' ,
    AUTH_TYPE VARCHAR(10)    		COMMENT '权限类型 role-角色，user-用户' ,
    OBJ_ID VARCHAR(50)    			COMMENT '对象ID' ,
    NODE_ID VARCHAR(50)    			COMMENT '节点ID' ,
    CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (AUTH_ID)
) COMMENT = '工作流节点权限 ';

CREATE TABLE SYS_WORKFLOW_MACRO_INFO(
    MACRO_ID VARCHAR(50) NOT NULL   	COMMENT '宏变量ID' ,
    MACRO_CODE VARCHAR(100) NOT NULL    COMMENT '宏变量标识' ,
	MACRO_NAME VARCHAR(100) NOT NULL    COMMENT '宏变量名称' ,
	MACRO_TYPE VARCHAR(10) NOT NULL    	COMMENT '宏变量类型 workflow/instance/node/auth-role/auth-user' ,
    WORKFLOW_ID VARCHAR(50) NOT NULL    COMMENT '工作流ID' ,
    MACRO_RMK VARCHAR(300)    			COMMENT '宏变量说明' ,
    CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (MACRO_ID)
) COMMENT = '工作流宏变量信息 ';

CREATE TABLE SYS_WORKFLOW_INSTANCE(
    INSTANCE_ID VARCHAR(50) NOT NULL   	COMMENT '实例ID' ,
    WORKFLOW_ID VARCHAR(50)    			COMMENT '工作流ID' ,
    INSTANCE_NAME VARCHAR(30)    		COMMENT '实例名称' ,
    INSTANCE_RMK VARCHAR(4000)    		COMMENT '实例说明' ,
	INSTANCE_STATUS	VARCHAR(1)			COMMENT '实例状态 0-未处理 1-处理中 2-已完成' ,
	CREATE_USER	VARCHAR(50)				COMMENT '创建用户' ,
	APP_ID 		VARCHAR(50) NOT NULL 	COMMENT '租户ID',
    CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (INSTANCE_ID)
) COMMENT = '工作流实例信息 ';

CREATE TABLE SYS_WORKFLOW_INST_NODE(
	INODE_ID VARCHAR(50) NOT NULL   COMMENT '实例节点ID' ,
    NODE_ID VARCHAR(50) NOT NULL   	COMMENT '流程节点ID' ,
    INSTANCE_ID VARCHAR(50)    		COMMENT '实例ID' ,
    NODE_STATUS VARCHAR(1)    		COMMENT '节点状态 0-未处理 1-通过 2-未通过 3-部分通过' ,
    ACTIVE_FLAG VARCHAR(1)    		COMMENT '当前节点' ,
    PRIMARY KEY (INODE_ID)
) COMMENT = '工作流实例节点信息 ';

CREATE TABLE SYS_WORKFLOW_INST_NODE_AUTH(
    AUTH_ID VARCHAR(50) NOT NULL   	COMMENT '流程权限ID' ,
    AUTH_TYPE VARCHAR(10)    		COMMENT '权限类型 role-角色，user-用户' ,
    OBJ_ID VARCHAR(50)    			COMMENT '对象ID' ,
    INODE_ID VARCHAR(50)    		COMMENT '实例节点ID' ,
    CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (AUTH_ID)
) COMMENT = '工作流实例节点权限 ';

CREATE TABLE SYS_WORKFLOW_INST_NODE_OPER(
    OPER_ID VARCHAR(50) NOT NULL   	COMMENT '操作ID' ,
    LOGIN_NAME VARCHAR(50)    		COMMENT '操作用户' ,
    AGREE_FLAG VARCHAR(1)    		COMMENT '是否同意 1-同意 0-不同意' ,
    OPER_RMK VARCHAR(500)    		COMMENT '处理意见' ,
    INODE_ID VARCHAR(50)    			COMMENT '节点ID' ,
    INSTANCE_ID VARCHAR(50)    		COMMENT '实例ID' ,
	OPER_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (OPER_ID)
) COMMENT = '工作流实例节点审批 ';

CREATE TABLE `SYS_DICT_ITEM` (
  `ID` VARCHAR(50) NOT NULL,
  `DICT_ID` VARCHAR(50) DEFAULT NULL COMMENT '字典ID',
  `ITEM_TEXT` VARCHAR(100) DEFAULT NULL COMMENT '字典项文本',
  `ITEM_VALUE` VARCHAR(100) DEFAULT NULL COMMENT '字典项值',
  `DESCRIPTION` VARCHAR(255) DEFAULT NULL COMMENT '描述',
  `SORT_ORDER` INT(10) DEFAULT NULL COMMENT '排序',
  `STATUS` INT(11) DEFAULT 1 COMMENT '状态（1启用 0不启用）',
  `CREATE_TIME` TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY (`ID`)
) COMMENT='字典明细表';

CREATE TABLE `SYS_DICT` (
  `ID` VARCHAR(50) NOT NULL,
  `DICT_NAME` VARCHAR(100) DEFAULT NULL COMMENT '字典名称',
  `DICT_CODE` VARCHAR(100) DEFAULT NULL COMMENT '字典编码',
  `DESCRIPTION` VARCHAR(255) DEFAULT NULL COMMENT '描述',
  `DEL_FLAG` INT(11) DEFAULT 1 COMMENT '删除状态(1，不删，0，删除)',
  `CREATE_TIME` TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP, 
  `TYPE` VARCHAR(255)DEFAULT '0' COMMENT '字典类型',
  PRIMARY KEY (`ID`)
) COMMENT='字典表';

CREATE TABLE SYS_USER_TASK_EXT(
    EXT_ID VARCHAR(50) NOT NULL   	COMMENT '任务扩展ID' ,
    EXT_NAME VARCHAR(200)    		COMMENT '任务扩展名称' ,
    UNDO_SQL text    				COMMENT '待处理任务SQL' ,
	DONE_SQL text					COMMENT '已处理任务SQL' ,
    EXT_URL VARCHAR(500)    		COMMENT '任务扩展URL' ,
	EXT_RMK VARCHAR(500)    		COMMENT '任务扩展描述' ,
    APP_ID 		VARCHAR(50) NOT NULL 	COMMENT '租户ID',
	CREATE_TIME  	TIMESTAMP COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP,
	MODIFY_TIME  	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (EXT_ID)
) COMMENT = '用户任务扩展表 ';

CREATE TABLE NOTICE_BUS_REL(
    SRV_ID VARCHAR(50)    COMMENT '服务器ID' ,
    BUS_ID VARCHAR(50) NOT NULL   COMMENT '业务数据ID' ,
    SRV_TYPE VARCHAR(6) NOT NULL   COMMENT '服务器类型' ,
    SRV_OPTIONS VARCHAR(300)    COMMENT '服务器属性内容' ,
    PRIMARY KEY (BUS_ID,SRV_TYPE)
) COMMENT = '通知方式与业务数据关系表 ';


CREATE TABLE SYS_LAYOUT_INFO (
  LAY_ID 		VARCHAR(50) NOT NULL COMMENT '主键',
  LAY_NAME 		VARCHAR(200) NOT NULL COMMENT '布局名称',
  APP_ID 		VARCHAR(50) DEFAULT NULL COMMENT '应用ID',
  LAY_TYPE 		CHAR(1) DEFAULT NULL COMMENT '布局类型，0-默认布局；1-权限布局；2-自定义布局',
  LAY_LEVEL 	INT(11) DEFAULT NULL COMMENT '应用ID',
  LOGIN_NAME 	VARCHAR(50) DEFAULT NULL COMMENT '登录名',
  LAY_RMK 		VARCHAR(500) DEFAULT NULL COMMENT '布局描述',
  CREATE_TIME 	TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY_TIME 	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (LAY_ID)
) COMMENT='布局信息表';

CREATE TABLE SYS_LAYOUT_ITEM_INFO (
  ITEM_ID 		VARCHAR(50) NOT NULL COMMENT '主键',
  ITEM_NAME 	VARCHAR(200) NOT NULL COMMENT '数据项名称',
  APP_ID 		VARCHAR(50) DEFAULT NULL COMMENT '应用ID',
  ITEM_COMP 	VARCHAR(400) DEFAULT NULL COMMENT '组件路径',
  MIN_WIDTH 	INT(11) DEFAULT NULL COMMENT '最小宽度',
  MIN_HEIGHT 	INT(11) DEFAULT NULL COMMENT '最小高度',
  LOGIN_NAME 	VARCHAR(50) DEFAULT NULL COMMENT '登录名',
  ITEM_ORDER 	INT(11) DEFAULT NULL COMMENT '数据项排序',
  ITEM_RMK 		VARCHAR(500) DEFAULT NULL COMMENT '数据项描述',
  CREATE_TIME 	TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY_TIME 	TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (ITEM_ID)
) COMMENT='布局数据项信息表';

CREATE TABLE SYS_LAYOUT_ITEM_REL (
  LAY_ID 		VARCHAR(50) NOT NULL COMMENT '布局ID',
  ITEM_ID 		VARCHAR(50) NOT NULL COMMENT '数据项ID',
  REL_X 		INT(11) NOT NULL COMMENT '列编号',
  REL_Y 		INT(11) NOT NULL COMMENT '行编号',
  REL_W 		INT(11) NOT NULL COMMENT '初始宽度',
  REL_H 		INT(11) NOT NULL COMMENT '初始高度',
  PRIMARY KEY (LAY_ID,ITEM_ID)
) COMMENT='布局-数据项关系表';

CREATE TABLE SYS_ROLE_LAYOUT_ITEM_REL (
  ROLE_ID 		VARCHAR(50) NOT NULL COMMENT '角色ID',
  ITEM_ID 		VARCHAR(50) NOT NULL COMMENT '数据项ID',
  PRIMARY KEY (ROLE_ID,ITEM_ID)
) COMMENT='角色-数据项权限表';

CREATE TABLE SYS_ROLE_LAYOUT_REL (
  ROLE_ID 		VARCHAR(50) NOT NULL COMMENT '角色ID',
  LAY_ID 		VARCHAR(50) NOT NULL COMMENT '布局ID',
  PRIMARY KEY (ROLE_ID,LAY_ID)
) COMMENT='角色-布局权限表';

CREATE TABLE SYS_USER_PWD_LOG_INFO (
  LOG_ID varchar(50) NOT NULL COMMENT '主键ID',
  LOGIN_NAME varchar(200) NOT NULL COMMENT '登录名',
  LOGIN_PWD varchar(200) NOT NULL COMMENT '密码',
  CREATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (LOG_ID)
) COMMENT='用户密码历史表';