CREATE TABLE SYS_OPERLOG_INFO(
    LOG_ID VARCHAR(50) NOT NULL,
    LOG_TYPE CHAR(1),
    LOG_STATUS CHAR(1)  NOT NULL,
    MODULE_NAME VARCHAR(255),
    ACTION_NAME VARCHAR(255),
    SERVICE_ID VARCHAR(50),
    REMOTE_ADDR VARCHAR(255),
    USER_AGENT VARCHAR(1000),
    REQUEST_URI VARCHAR(1000),
    METHOD_NAME VARCHAR(10),
    PARAMS CLOB(65535),
    OPER_TIME VARCHAR(10),
    EXCEPTION_STR CLOB(65535),
    DEL_FLAG CHAR(1),
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP,
    PRIMARY KEY (LOG_ID)
);
COMMENT ON TABLE SYS_OPERLOG_INFO IS '操作日志表';
COMMENT ON COLUMN SYS_OPERLOG_INFO.LOG_ID IS '主键';
COMMENT ON COLUMN SYS_OPERLOG_INFO.LOG_TYPE IS '日志类型';
COMMENT ON COLUMN SYS_OPERLOG_INFO.LOG_STATUS IS '操作状态  0 成功 1 失败';
COMMENT ON COLUMN SYS_OPERLOG_INFO.MODULE_NAME IS '模块名';
COMMENT ON COLUMN SYS_OPERLOG_INFO.ACTION_NAME IS '操作名';
COMMENT ON COLUMN SYS_OPERLOG_INFO.SERVICE_ID IS '服务ID';
COMMENT ON COLUMN SYS_OPERLOG_INFO.REMOTE_ADDR IS '操作IP地址';
COMMENT ON COLUMN SYS_OPERLOG_INFO.USER_AGENT IS '用户代理';
COMMENT ON COLUMN SYS_OPERLOG_INFO.REQUEST_URI IS '请求URI';
COMMENT ON COLUMN SYS_OPERLOG_INFO.METHOD_NAME IS '操作方式';
COMMENT ON COLUMN SYS_OPERLOG_INFO.PARAMS IS '操作提交的数据';
COMMENT ON COLUMN SYS_OPERLOG_INFO.OPER_TIME IS '执行时间';
COMMENT ON COLUMN SYS_OPERLOG_INFO.EXCEPTION_STR IS '异常信息';
COMMENT ON COLUMN SYS_OPERLOG_INFO.DEL_FLAG IS '删除标记';
COMMENT ON COLUMN SYS_OPERLOG_INFO.CREATE_BY IS '创建者';
COMMENT ON COLUMN SYS_OPERLOG_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_OPERLOG_INFO.UPDATE_TIME IS '更新时间';
COMMENT ON TABLE SYS_OPERLOG_INFO IS '操作日志表';

CREATE TABLE SYS_OAUTH_CLIENT(
   CLIENT_ID              		VARCHAR(100) NOT NULL,
	RESOURCES_IDS          		VARCHAR(256) NULL,
	CLIENT_SECRET          		VARCHAR(256) NULL,
	SCOPE                  		VARCHAR(256) NULL,
	AUTHORIZED_GRANT_TYPES 		VARCHAR(256) NULL,
	WEB_SERVER_REDIRECT_URI		VARCHAR(256) NULL,
	AUTHORITIES                	VARCHAR(256) NULL,
	ACCESS_TOKEN_VALIDITY  		INTEGER NULL,
	REFRESH_TOKEN_VALIDITY 		INTEGER NULL,
	ADDITION_INFORMATION   		VARCHAR(4096) NULL,
	AUTOAPPROVE                	VARCHAR(256) NULL,
	PRIMARY KEY(CLIENT_ID)
);
COMMENT ON TABLE SYS_OAUTH_CLIENT IS 'OAUTH2客户端资源认证表';

CREATE TABLE SYS_MENU_INFO(
    MENU_ID         	VARCHAR(50) 	NOT NULL,
	MENU_NAME       	VARCHAR(100) 	NOT NULL,
	MENU_ROUTE_NAME     VARCHAR(100),
	MENU_TYPE       	VARCHAR(1) 		NOT NULL,
	MENU_URL        	VARCHAR(500),
	HTTP_METHOD     	VARCHAR(20),
	MENU_PATH       	VARCHAR(300),
	BUTTON_PERMISSION 	VARCHAR(100),
	MENU_COLOR      	VARCHAR(50),
	PARENT_ID  			VARCHAR(50)     NOT NULL,
	MENU_ICON       	VARCHAR(50),
	COMPONENT_PATH  	VARCHAR(300),
	MENU_SORT       	INTEGER,
	CREATE_TIME			TIMESTAMP  		NOT NULL,
	MODIFY_TIME			TIMESTAMP ,
	DEL_FLAG   			VARCHAR(1) ,
	APP_ID 				VARCHAR(50),
	AUTH_FLAG 			CHAR(1),
	HIDE_FLAG 			CHAR(1),
	ALIVE_FLAG 			CHAR(1),
    PRIMARY KEY (MENU_ID)
);
COMMENT ON TABLE SYS_MENU_INFO IS '菜单表';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_ID IS '主键';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_NAME IS '菜单名称';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_ROUTE_NAME IS '菜单路径名称,用于多语言标识';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_TYPE IS '菜单类型 0-菜单 1-按钮';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_URL IS '后台请求URL';
COMMENT ON COLUMN SYS_MENU_INFO.HTTP_METHOD IS '请求方式';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_PATH IS '前端URL';
COMMENT ON COLUMN SYS_MENU_INFO.BUTTON_PERMISSION IS '按钮权限资源标识';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_COLOR IS '颜色';
COMMENT ON COLUMN SYS_MENU_INFO.PARENT_ID IS '父资源ID';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_ICON IS '图标';
COMMENT ON COLUMN SYS_MENU_INFO.COMPONENT_PATH IS '组件路径';
COMMENT ON COLUMN SYS_MENU_INFO.MENU_SORT IS '排序权重';
COMMENT ON COLUMN SYS_MENU_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_MENU_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SYS_MENU_INFO.DEL_FLAG IS '是否删除 1-删除，0-未删除';
COMMENT ON COLUMN SYS_MENU_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_MENU_INFO.AUTH_FLAG IS '权限标识:0-不需要权限;1-需要权限';
COMMENT ON COLUMN SYS_MENU_INFO.HIDE_FLAG IS '隐藏菜单：0-否;1-是';
COMMENT ON COLUMN SYS_MENU_INFO.ALIVE_FLAG IS '缓存组件：0-否;1-是';
COMMENT ON TABLE SYS_MENU_INFO IS '菜单表';

CREATE TABLE SYS_ROLE_MENU_REL(
    ROLE_ID VARCHAR(50) NOT NULL,
    MENU_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (ROLE_ID,MENU_ID)
);
COMMENT ON TABLE SYS_ROLE_MENU_REL IS '角色菜单关联表';
COMMENT ON COLUMN SYS_ROLE_MENU_REL.ROLE_ID IS '主键';
COMMENT ON COLUMN SYS_ROLE_MENU_REL.MENU_ID IS '主键';
COMMENT ON TABLE SYS_ROLE_MENU_REL IS '角色菜单关联表';

CREATE TABLE SYS_ROLE_INFO(
    ROLE_ID 		VARCHAR(50)  	NOT NULL,
    ROLE_CODE 		VARCHAR(50)  	NOT NULL,
    ROLE_NAME 		VARCHAR(128)  	NOT NULL,
    APP_ID 			VARCHAR(50) 	NOT NULL,
    CREATE_TIME 	TIMESTAMP 		NOT NULL,
    MODIFY_TIME 	TIMESTAMP,
    DEL_FLAG	 	VARCHAR(50),
    PRIMARY KEY (ROLE_ID)
);
COMMENT ON TABLE SYS_ROLE_INFO IS '角色表';
COMMENT ON COLUMN SYS_ROLE_INFO.ROLE_ID IS '主键';
COMMENT ON COLUMN SYS_ROLE_INFO.ROLE_CODE IS '角色CODE用于SPRINGSECURITY角色标识码';
COMMENT ON COLUMN SYS_ROLE_INFO.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN SYS_ROLE_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_ROLE_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_ROLE_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SYS_ROLE_INFO.DEL_FLAG IS '是否删除 1-删除，0-未删除';
COMMENT ON TABLE SYS_ROLE_INFO IS '角色表';

CREATE TABLE SYS_ROLE_USER_REL(
    USER_ID VARCHAR(50) NOT NULL,
    ROLE_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (USER_ID,ROLE_ID)
);
COMMENT ON TABLE SYS_ROLE_USER_REL IS '用户角色关联表';
COMMENT ON COLUMN SYS_ROLE_USER_REL.USER_ID IS '主键';
COMMENT ON COLUMN SYS_ROLE_USER_REL.ROLE_ID IS '主键';
COMMENT ON TABLE SYS_ROLE_USER_REL IS '用户角色关联表';

CREATE TABLE SYS_USER_INFO(
    USER_ID VARCHAR(50) NOT NULL,
    LOGIN_NAME VARCHAR(100)  NOT NULL,
    USER_NAME VARCHAR(200)  NOT NULL,
    LOGIN_PWD VARCHAR(200) NOT NULL,
    USER_EMAIL VARCHAR(200),
    USER_MOB_TEL VARCHAR(30)  NOT NULL,
    DEL_FLAG CHAR(1),
    BRANCH_NO VARCHAR(50) NOT NULL,
    CRYPT_PWD VARCHAR(200) NOT NULL,
    APP_ID VARCHAR(50),
	LOGIN_TIME  TIMESTAMP,
    CREATE_TIME TIMESTAMP NOT NULL,
    MODIFY_TIME TIMESTAMP,
    PRIMARY KEY (USER_ID)
);
COMMENT ON TABLE SYS_USER_INFO IS '用户表';
COMMENT ON COLUMN SYS_USER_INFO.USER_ID IS '主键ID';
COMMENT ON COLUMN SYS_USER_INFO.LOGIN_NAME IS '登录名';
COMMENT ON COLUMN SYS_USER_INFO.USER_NAME IS '用户名';
COMMENT ON COLUMN SYS_USER_INFO.LOGIN_PWD IS '密码';
COMMENT ON COLUMN SYS_USER_INFO.USER_EMAIL IS '邮箱';
COMMENT ON COLUMN SYS_USER_INFO.USER_MOB_TEL IS '手机号码';
COMMENT ON COLUMN SYS_USER_INFO.DEL_FLAG IS '是否删除 0-未删除 1-删除';
COMMENT ON COLUMN SYS_USER_INFO.BRANCH_NO IS '机构编号';
COMMENT ON COLUMN SYS_USER_INFO.CRYPT_PWD IS '内部加密密码';
COMMENT ON COLUMN SYS_USER_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_USER_INFO.LOGIN_TIME IS '登录时间';
COMMENT ON COLUMN SYS_USER_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_USER_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_USER_INFO IS '用户表';

CREATE TABLE SYS_ZUUL_ROUTE(
    ROUTE_ID		VARCHAR(50)  NOT NULL,
    ROUTE_PATH 		VARCHAR(255)  NOT NULL,
    SERVICE_ID 		VARCHAR(255) NOT NULL,
    URL_PROXY 		VARCHAR(255),
    STRIP_PREFIX 	CHAR(1),
    RETRYABLE_FLAG 	CHAR(1),
    ENABLED_FLAG 	CHAR(1),
    HEADERS_LIST 	VARCHAR(255),
    CREATE_TIME 	TIMESTAMP NOT NULL,
    UPDATE_TIME 	TIMESTAMP,
    DEL_FLAG 		CHAR(1),
    PRIMARY KEY (ROUTE_ID)
);
COMMENT ON TABLE SYS_ZUUL_ROUTE IS '动态路由配置表';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.ROUTE_ID IS 'ROUTER ID';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.ROUTE_PATH IS '路由路径';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.SERVICE_ID IS '服务名称';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.URL_PROXY IS 'URL代理';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.STRIP_PREFIX IS '转发去掉前缀';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.RETRYABLE_FLAG IS '是否重试';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.ENABLED_FLAG IS '是否启用';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.HEADERS_LIST IS '敏感请求头';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_ZUUL_ROUTE.DEL_FLAG IS '删除标识（0-正常,1-删除）';
COMMENT ON TABLE SYS_ZUUL_ROUTE IS '动态路由配置表';

CREATE TABLE SYS_ANNO_TYPE_INFO(
    TYPE_ID		VARCHAR(50) 	NOT NULL,
    APP_ID 		VARCHAR(50) 	NOT NULL,
    TYPE_NAME	VARCHAR(50)  	NOT NULL,
    CREATE_TIME TIMESTAMP  		NOT NULL,
    MODIFY_TIME TIMESTAMP,
    TYPE_RMK VARCHAR(500),
    PRIMARY KEY (TYPE_ID)
);
COMMENT ON TABLE SYS_ANNO_TYPE_INFO IS '公告类型信息表';
COMMENT ON COLUMN SYS_ANNO_TYPE_INFO.TYPE_ID IS '主键ID';
COMMENT ON COLUMN SYS_ANNO_TYPE_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_ANNO_TYPE_INFO.TYPE_NAME IS '类型名称';
COMMENT ON COLUMN SYS_ANNO_TYPE_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_ANNO_TYPE_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SYS_ANNO_TYPE_INFO.TYPE_RMK IS '类型描述';
COMMENT ON TABLE SYS_ANNO_TYPE_INFO IS '公告类型信息表';

CREATE TABLE SYS_ANNO_INFO(
  ANNO_ID 		VARCHAR(50) 	NOT NULL,
  ANNO_LEVEL 	CHAR(1) 		NOT NULL ,
  IS_VALID 		SMALLINT		NOT NULL ,
  ANNO_TITLE 	VARCHAR(255) 	NOT NULL,
  ANNO_CONTENT 	CLOB(16777215),
  LOGIN_NAME 	VARCHAR(50) 	NOT NULL,
  TYPE_ID 		VARCHAR(50) 	NOT NULL,
  START_TIME 	TIMESTAMP,
  END_TIME 		TIMESTAMP,
  APP_ID 		VARCHAR(50) 	NOT NULL,
  CREATE_TIME  	TIMESTAMP 		NOT NULL,
  MODIFY_TIME  	TIMESTAMP ,
  PRIMARY KEY (ANNO_ID)
);
COMMENT ON TABLE SYS_ANNO_INFO IS '公告信息表';
COMMENT ON COLUMN SYS_ANNO_INFO.ANNO_ID IS '公告ID';
COMMENT ON COLUMN SYS_ANNO_INFO.ANNO_LEVEL IS '公告等级';
COMMENT ON COLUMN SYS_ANNO_INFO.IS_VALID IS '是否有效';
COMMENT ON COLUMN SYS_ANNO_INFO.ANNO_TITLE IS '公告标题';
COMMENT ON COLUMN SYS_ANNO_INFO.ANNO_CONTENT IS '公告内容';
COMMENT ON COLUMN SYS_ANNO_INFO.LOGIN_NAME IS '登录名';
COMMENT ON COLUMN SYS_ANNO_INFO.TYPE_ID IS '公告类型ID';
COMMENT ON COLUMN SYS_ANNO_INFO.START_TIME IS '公告有效期：生效时间';
COMMENT ON COLUMN SYS_ANNO_INFO.END_TIME IS '公告有效期：结束时间';
COMMENT ON COLUMN SYS_ANNO_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_ANNO_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_ANNO_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_ANNO_INFO IS '公告信息表';

CREATE TABLE SYS_ANNO_ATTACH_INFO(
    ATT_ID VARCHAR(50) NOT NULL,
  	ANNO_ID VARCHAR(50) NOT NULL,
  	APP_ID VARCHAR(50) NOT NULL,
  	ATT_NAME VARCHAR(200) NOT NULL,
  	ATT_CONTENT BLOB(16777215) NOT NULL,
    PRIMARY KEY (ATT_ID)
);
COMMENT ON TABLE SYS_ANNO_ATTACH_INFO IS '公告附件信息表';
COMMENT ON COLUMN SYS_ANNO_ATTACH_INFO.ATT_ID IS '附件ID';
COMMENT ON COLUMN SYS_ANNO_ATTACH_INFO.ANNO_ID IS '公告ID';
COMMENT ON COLUMN SYS_ANNO_ATTACH_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_ANNO_ATTACH_INFO.ATT_NAME IS '附件名称';
COMMENT ON COLUMN SYS_ANNO_ATTACH_INFO.ATT_CONTENT IS '附件内容';
COMMENT ON TABLE SYS_ANNO_ATTACH_INFO IS '公告附件信息表';

CREATE TABLE SYS_ANNO_USER_OPER(
    ANNO_ID VARCHAR(50) NOT NULL,
  USER_ID VARCHAR(50) NOT NULL,
  READ_FLAG VARCHAR(1) NOT NULL,
  DELE_FLAG VARCHAR(1) NOT NULL,
    PRIMARY KEY (ANNO_ID,USER_ID)
);
COMMENT ON TABLE SYS_ANNO_USER_OPER IS '公告用户状态表';
COMMENT ON COLUMN SYS_ANNO_USER_OPER.ANNO_ID IS '公告ID';
COMMENT ON COLUMN SYS_ANNO_USER_OPER.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_ANNO_USER_OPER.READ_FLAG IS '0-未读, 1-已读';
COMMENT ON COLUMN SYS_ANNO_USER_OPER.DELE_FLAG IS '0-未删除, 1-已删除';
COMMENT ON TABLE SYS_ANNO_USER_OPER IS '公告用户状态表';

CREATE TABLE SYS_USER_GROUP_REL(
    GROUP_ID VARCHAR(50) NOT NULL,
    USER_ID  VARCHAR(50) NOT NULL,
    PRIMARY KEY (GROUP_ID,USER_ID)
);
COMMENT ON TABLE SYS_USER_GROUP_REL IS '用户组关系表';
COMMENT ON COLUMN SYS_USER_GROUP_REL.GROUP_ID IS '用户组ID';
COMMENT ON COLUMN SYS_USER_GROUP_REL.USER_ID IS '用户ID';
COMMENT ON TABLE SYS_USER_GROUP_REL IS '用户组关系表';

CREATE TABLE SYS_USER_GROUP_INFO(
    GROUP_ID VARCHAR(50) NOT NULL,
    GROUP_NAME VARCHAR(300),
    GROUP_RMK VARCHAR(500),
    APP_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (GROUP_ID)
);
COMMENT ON TABLE SYS_USER_GROUP_INFO IS '用户组';
COMMENT ON COLUMN SYS_USER_GROUP_INFO.GROUP_ID IS '用户组ID';
COMMENT ON COLUMN SYS_USER_GROUP_INFO.GROUP_NAME IS '用户组名称';
COMMENT ON COLUMN SYS_USER_GROUP_INFO.GROUP_RMK IS '用户组描述';
COMMENT ON COLUMN SYS_USER_GROUP_INFO.APP_ID IS '租户ID';
COMMENT ON TABLE SYS_USER_GROUP_INFO IS '用户组';

CREATE TABLE SYS_GROUP_BRANCH_REL(
    GROUP_ID  VARCHAR(50)  NOT NULL,
    BRANCH_NO  VARCHAR(50)  NOT NULL,
    PRIMARY KEY (GROUP_ID,BRANCH_NO)
);
COMMENT ON TABLE SYS_GROUP_BRANCH_REL IS '用户机构关系表';
COMMENT ON COLUMN SYS_GROUP_BRANCH_REL.GROUP_ID IS '用户组ID';
COMMENT ON COLUMN SYS_GROUP_BRANCH_REL.BRANCH_NO IS '机构号';
COMMENT ON TABLE SYS_GROUP_BRANCH_REL IS '用户机构关系表';

CREATE TABLE SYS_DBLINK_INFO(
    DBLINK_ID VARCHAR(50)  NOT NULL,
    DBLINK_NAME VARCHAR(255)  NOT NULL,
    DBLINK_RMK VARCHAR(500),
    DBLINK_TYPE CHAR(1) NOT NULL,
    DBLINK_DRIVER VARCHAR(50) NOT NULL,
    DBLINK_URL VARCHAR(200) NOT NULL,
    DBLINK_USER VARCHAR(50) NOT NULL,
    DBLINK_PWD VARCHAR(50) NOT NULL,
    POOL_TYPE CHAR(1),
    CREATE_TIME TIMESTAMP NOT NULL,
    MODIFY_TIME TIMESTAMP,
    INITIAL_SIZE INTEGER,
    MAX_ACTIVE INTEGER,
    MIN_IDLE INTEGER,
    CACHE_FLAG CHAR(1),
    MAX_PS_CATCH INTEGER,
    VALIDATION_QUERY VARCHAR(100),
    MAX_WAIT INTEGER,
    TEST_ON_BORROW CHAR(1),
    TEST_ON_RETURN CHAR(1),
    TEST_WHILE_IDLE CHAR(1),
    TIME_BTN_EVICTION_RUNS_MILLIS INTEGER,
    MIN_EVICTABLE_IDLE_TIME_MILLIS INTEGER,
    POOL_PREPARED_STATEMENTS CHAR(1),
    MAX_PS_CATCH_SIZE INTEGER,
    REMOVE_ABANDONED CHAR(1),
    REMOVE_ABANDONED_TIMEOUT INTEGER,
    FILTERS VARCHAR(100) ,
    PRIMARY KEY (DBLINK_ID)
);
COMMENT ON TABLE SYS_DBLINK_INFO IS '数据源信息表';
COMMENT ON COLUMN SYS_DBLINK_INFO.DBLINK_ID IS '数据源ID';
COMMENT ON COLUMN SYS_DBLINK_INFO.DBLINK_NAME IS '数据源英文名';
COMMENT ON COLUMN SYS_DBLINK_INFO.DBLINK_RMK IS '数据源描述';
COMMENT ON COLUMN SYS_DBLINK_INFO.DBLINK_TYPE IS '数据源类型';
COMMENT ON COLUMN SYS_DBLINK_INFO.DBLINK_DRIVER IS '驱动';
COMMENT ON COLUMN SYS_DBLINK_INFO.DBLINK_URL IS 'URL';
COMMENT ON COLUMN SYS_DBLINK_INFO.DBLINK_USER IS '用户';
COMMENT ON COLUMN SYS_DBLINK_INFO.DBLINK_PWD IS '密码';
COMMENT ON COLUMN SYS_DBLINK_INFO.POOL_TYPE IS '连接池类型';
COMMENT ON COLUMN SYS_DBLINK_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_DBLINK_INFO.MODIFY_TIME IS '修改时间';
COMMENT ON COLUMN SYS_DBLINK_INFO.INITIAL_SIZE IS '初始化时物理连接个数';
COMMENT ON COLUMN SYS_DBLINK_INFO.MAX_ACTIVE IS '最大连接池数量';
COMMENT ON COLUMN SYS_DBLINK_INFO.MIN_IDLE IS '最小连接池数量';
COMMENT ON COLUMN SYS_DBLINK_INFO.CACHE_FLAG IS '缓存标识';
COMMENT ON COLUMN SYS_DBLINK_INFO.MAX_PS_CATCH IS '最大缓存数量';
COMMENT ON COLUMN SYS_DBLINK_INFO.VALIDATION_QUERY IS '参数SQL';
COMMENT ON COLUMN SYS_DBLINK_INFO.MAX_WAIT IS '获取连接等待超时时间';
COMMENT ON COLUMN SYS_DBLINK_INFO.TEST_ON_BORROW IS '取连接时是否检查连接有效性';
COMMENT ON COLUMN SYS_DBLINK_INFO.TEST_ON_RETURN IS '归还连接时是否检查连接有效性';
COMMENT ON COLUMN SYS_DBLINK_INFO.TEST_WHILE_IDLE IS '获取连接时是否检查连接有效性';
COMMENT ON COLUMN SYS_DBLINK_INFO.TIME_BTN_EVICTION_RUNS_MILLIS IS '检测周期';
COMMENT ON COLUMN SYS_DBLINK_INFO.MIN_EVICTABLE_IDLE_TIME_MILLIS IS '最大空闲时间';
COMMENT ON COLUMN SYS_DBLINK_INFO.POOL_PREPARED_STATEMENTS IS 'PSCACHE打开标识';
COMMENT ON COLUMN SYS_DBLINK_INFO.MAX_PS_CATCH_SIZE IS 'PSCATCH缓存最大数';
COMMENT ON COLUMN SYS_DBLINK_INFO.REMOVE_ABANDONED IS '泄漏检查标识';
COMMENT ON COLUMN SYS_DBLINK_INFO.REMOVE_ABANDONED_TIMEOUT IS '超时时间';
COMMENT ON COLUMN SYS_DBLINK_INFO.FILTERS IS '扩展插件';
COMMENT ON TABLE SYS_DBLINK_INFO IS '数据源信息表';

CREATE TABLE NOTICE_MAIL_SEND_LOG(
    LOG_ID VARCHAR(50)  NOT NULL,
    LOG_STATE CHAR(1)  NOT NULL,
    LOGIN_NAME VARCHAR(50)  NOT NULL,
    SRV_ID VARCHAR(50)  NOT NULL,
    TEMP_ID VARCHAR(50)  NOT NULL,
    ERROR_STR VARCHAR(2000) ,
    CREATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (LOG_ID)
);
COMMENT ON TABLE NOTICE_MAIL_SEND_LOG IS '邮件日志信息表';
COMMENT ON COLUMN NOTICE_MAIL_SEND_LOG.LOG_ID IS '日志ID';
COMMENT ON COLUMN NOTICE_MAIL_SEND_LOG.LOG_STATE IS '发送状态';
COMMENT ON COLUMN NOTICE_MAIL_SEND_LOG.LOGIN_NAME IS '用户登录名';
COMMENT ON COLUMN NOTICE_MAIL_SEND_LOG.SRV_ID IS '服务器ID';
COMMENT ON COLUMN NOTICE_MAIL_SEND_LOG.TEMP_ID IS '模板ID';
COMMENT ON COLUMN NOTICE_MAIL_SEND_LOG.ERROR_STR IS '异常信息';
COMMENT ON COLUMN NOTICE_MAIL_SEND_LOG.CREATE_TIME IS '发送时间';
COMMENT ON TABLE NOTICE_MAIL_SEND_LOG IS '邮件日志信息表';

CREATE TABLE NOTICE_MAIL_SRV_INFO(
    SRV_ID VARCHAR(50)  NOT NULL,
    SRV_NAME VARCHAR(200)  NOT NULL,
    SRV_RMK VARCHAR(300) ,
    SRV_URL VARCHAR(200)  NOT NULL,
    SRV_PORT INTEGER  NOT NULL,
    LOGIN_NAME VARCHAR(50) ,
    LOGIN_PWD VARCHAR(50) ,
    DEFAULT_FROM VARCHAR(50)  NOT NULL,
    SHOW_NAME VARCHAR(100) ,
    SSL_FLAG CHAR(1)  NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    MODIFY_TIME TIMESTAMP,
    APP_ID  VARCHAR(50) NOT NULL,
    PRIMARY KEY (SRV_ID)
);
COMMENT ON TABLE NOTICE_MAIL_SRV_INFO IS '邮件服务器信息表';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.SRV_ID IS '服务器标识';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.SRV_NAME IS '服务器名称';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.SRV_RMK IS '服务器描述';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.SRV_URL IS '服务器地址';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.SRV_PORT IS '服务器端口';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.LOGIN_NAME IS '用户名';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.LOGIN_PWD IS '密码';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.DEFAULT_FROM IS '邮箱地址';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.SHOW_NAME IS '显示名称';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.SSL_FLAG IS '是否启用SSL';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN NOTICE_MAIL_SRV_INFO.APP_ID IS '租户ID';
COMMENT ON TABLE NOTICE_MAIL_SRV_INFO IS '邮件服务器信息表';

CREATE TABLE NOTICE_MAIL_TEMP_INFO(
    TEMP_ID VARCHAR(50)  NOT NULL,
    TEMP_NAME VARCHAR(50)  NOT NULL,
    TEMP_CONTENT VARCHAR(50) ,
    CREATE_TIME TIMESTAMP NOT NULL,
    MODIFY_TIME TIMESTAMP,
    APP_ID  VARCHAR(50) NOT NULL,
    PRIMARY KEY (TEMP_ID)
);
COMMENT ON TABLE NOTICE_MAIL_TEMP_INFO IS '邮件模板';
COMMENT ON COLUMN NOTICE_MAIL_TEMP_INFO.TEMP_ID IS '模板ID';
COMMENT ON COLUMN NOTICE_MAIL_TEMP_INFO.TEMP_NAME IS '模板名称';
COMMENT ON COLUMN NOTICE_MAIL_TEMP_INFO.TEMP_CONTENT IS '模板内容';
COMMENT ON COLUMN NOTICE_MAIL_TEMP_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN NOTICE_MAIL_TEMP_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN NOTICE_MAIL_TEMP_INFO.APP_ID IS '租户ID';
COMMENT ON TABLE NOTICE_MAIL_TEMP_INFO IS '邮件模板';

CREATE TABLE SYS_TASK_INFO(
    TASK_ID VARCHAR(50)  NOT NULL,
    TASK_NAME VARCHAR(255)  NOT NULL,
    EXEC_CLASS VARCHAR(100)  NOT NULL,
    EXEC_METHOD VARCHAR(50)  NOT NULL,
    TRIGGER_ID VARCHAR(50)  NOT NULL,
    START_TIME VARCHAR(32)  NOT NULL,
    END_TIME VARCHAR(32)  NOT NULL,
    TASK_STATUS CHAR(1)  NOT NULL,
    LOGIN_NAME VARCHAR(50)  NOT NULL,
    TASK_RMK VARCHAR(500) ,
    EXT_ATTR1  VARCHAR(100),
    EXT_ATTR2  VARCHAR(100),
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    DEL_FLAG CHAR(1),
    PRIMARY KEY (TASK_ID)
);
COMMENT ON TABLE SYS_TASK_INFO IS '调度任务信息表';
COMMENT ON COLUMN SYS_TASK_INFO.TASK_ID IS '任务ID';
COMMENT ON COLUMN SYS_TASK_INFO.TASK_NAME IS '任务名称';
COMMENT ON COLUMN SYS_TASK_INFO.EXEC_CLASS IS '执行类';
COMMENT ON COLUMN SYS_TASK_INFO.EXEC_METHOD IS '执行函数';
COMMENT ON COLUMN SYS_TASK_INFO.TRIGGER_ID IS '调度策略ID';
COMMENT ON COLUMN SYS_TASK_INFO.START_TIME IS '开始时间';
COMMENT ON COLUMN SYS_TASK_INFO.END_TIME IS '结束时间';
COMMENT ON COLUMN SYS_TASK_INFO.TASK_STATUS IS '任务状态';
COMMENT ON COLUMN SYS_TASK_INFO.LOGIN_NAME IS '创建任务用户登录名';
COMMENT ON COLUMN SYS_TASK_INFO.TASK_RMK IS '任务描述';
COMMENT ON COLUMN SYS_TASK_INFO.EXT_ATTR1 IS '拓展属性1';
COMMENT ON COLUMN SYS_TASK_INFO.EXT_ATTR2 IS '拓展属性2';
COMMENT ON COLUMN SYS_TASK_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_TASK_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SYS_TASK_INFO.DEL_FLAG IS '删除标识';
COMMENT ON TABLE SYS_TASK_INFO IS '调度任务信息表';

CREATE TABLE SYS_TASK_LOG_INFO(
    LOG_ID VARCHAR(50)  NOT NULL,
    TASK_ID VARCHAR(50) ,
    TASK_NAME VARCHAR(255) ,
    EXEC_STATUS  CHAR(1),
    CREATE_TIME TIMESTAMP  NOT NULL,
    LOG_CONTENT  VARCHAR(2000),
    PRIMARY KEY (LOG_ID)
);
COMMENT ON TABLE SYS_TASK_LOG_INFO IS '调度日志信息表';
COMMENT ON COLUMN SYS_TASK_LOG_INFO.LOG_ID IS '日志ID';
COMMENT ON COLUMN SYS_TASK_LOG_INFO.TASK_ID IS '任务ID';
COMMENT ON COLUMN SYS_TASK_LOG_INFO.TASK_NAME IS '任务名称';
COMMENT ON COLUMN SYS_TASK_LOG_INFO.EXEC_STATUS IS '执行状态';
COMMENT ON COLUMN SYS_TASK_LOG_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_TASK_LOG_INFO.LOG_CONTENT IS '日志内容';
COMMENT ON TABLE SYS_TASK_LOG_INFO IS '调度日志信息表';

CREATE TABLE SYS_TASK_TRIGGER_INFO(
    TRIGGER_ID VARCHAR(50)  NOT NULL,
    TRIGGER_NAME VARCHAR(255)  NOT NULL,
    TRIGGER_TYPE CHAR(1)  NOT NULL,
    CRON_EXPRESSION VARCHAR(100) ,
    REPEAT_COUNT INTEGER,
    REPEAT_INTERVAL INTEGER,
    START_DELAY INTEGER,
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    DEL_FLAG  CHAR(1),
    PRIMARY KEY (TRIGGER_ID)
);
COMMENT ON TABLE SYS_TASK_TRIGGER_INFO IS '调度策略信息表';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.TRIGGER_ID IS '策略ID';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.TRIGGER_NAME IS '策略名称';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.TRIGGER_TYPE IS '策略类型';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.CRON_EXPRESSION IS 'CRON表达式';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.REPEAT_COUNT IS '调度次数';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.REPEAT_INTERVAL IS '调度间隔';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.START_DELAY IS '调度延迟时间';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SYS_TASK_TRIGGER_INFO.DEL_FLAG IS '删除标识';
COMMENT ON TABLE SYS_TASK_TRIGGER_INFO IS '调度策略信息表';

CREATE TABLE SYS_FILE_SERVER_INFO(
    FILE_SERVER_ID VARCHAR(50)  NOT NULL,
    FILE_SERVER_NAME VARCHAR(255) NOT NULL,
    FILE_SERVER_RMK VARCHAR(500),
    FILE_SERVER_TYPE CHAR(1) NOT NULL,
    FILE_SERVER_IP VARCHAR(50),
    FILE_SERVER_PORT VARCHAR(20),
    FILE_SERVER_USER VARCHAR(50),
    FILE_SERVER_PWD VARCHAR(50),
    PROTOCOL VARCHAR(100) NOT NULL,
    FILE_SERVER_PATH VARCHAR(500),
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    DEL_FLAG CHAR(1) NOT NULL,
    PRIMARY KEY (FILE_SERVER_ID)
);
COMMENT ON TABLE SYS_FILE_SERVER_INFO IS '文件服务器信息表';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_ID IS '文件服务器ID';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_NAME IS '名称';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_RMK IS '描述';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_TYPE IS '服务器类型';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_IP IS 'IP地址';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_PORT IS '端口号';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_USER IS '用户';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_PWD IS '密码';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.PROTOCOL IS '协议';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.FILE_SERVER_PATH IS '目录';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_FILE_SERVER_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_FILE_SERVER_INFO IS '文件服务器信息表';

CREATE TABLE SYS_BRANCH_INFO(
    BRANCH_NO VARCHAR(200) NOT NULL,
    BRANCH_NAME VARCHAR(255),
    BRANCH_SHORT_NAME VARCHAR(255),
    BRANCH_TYPE CHAR(1),
    PARENT_BRANCH_NO VARCHAR(200),
    ET_FLAG CHAR(1),
    VIR_FLAG CHAR(1),
    PRIMARY KEY (BRANCH_NO)
);
COMMENT ON TABLE SYS_BRANCH_INFO IS '机构信息表';
COMMENT ON COLUMN SYS_BRANCH_INFO.BRANCH_NO IS '机构号';
COMMENT ON COLUMN SYS_BRANCH_INFO.BRANCH_NAME IS '机构名称';
COMMENT ON COLUMN SYS_BRANCH_INFO.BRANCH_SHORT_NAME IS '机构简称';
COMMENT ON COLUMN SYS_BRANCH_INFO.BRANCH_TYPE IS '机构类型';
COMMENT ON COLUMN SYS_BRANCH_INFO.PARENT_BRANCH_NO IS '父级机构编号';
COMMENT ON COLUMN SYS_BRANCH_INFO.ET_FLAG IS 'ETL同步';
COMMENT ON COLUMN SYS_BRANCH_INFO.VIR_FLAG IS '是否是虚拟机构';
COMMENT ON TABLE SYS_BRANCH_INFO IS '机构信息表';

CREATE TABLE SYS_HELP_FILE_INFO(
    HELP_FILE_ID VARCHAR(50)  NOT NULL,
    HELP_FILE_NAME VARCHAR(300) ,
    HELP_FILE_SIZE INTEGER ,
    HELP_FILE_TYPE VARCHAR(10) ,
	HELP_FILE_CONTENT blob,
    PRIMARY KEY (HELP_FILE_ID)
);
COMMENT ON TABLE SYS_HELP_FILE_INFO IS '帮助文档信息表';
COMMENT ON COLUMN SYS_HELP_FILE_INFO.HELP_FILE_ID IS '帮助文档ID';
COMMENT ON COLUMN SYS_HELP_FILE_INFO.HELP_FILE_NAME IS '帮助文档名称';
COMMENT ON COLUMN SYS_HELP_FILE_INFO.HELP_FILE_SIZE IS '帮助文档大小';
COMMENT ON COLUMN SYS_HELP_FILE_INFO.HELP_FILE_TYPE IS '帮助文档类型';
COMMENT ON COLUMN SYS_HELP_FILE_INFO.HELP_FILE_CONTENT IS '帮助文档文件';
COMMENT ON TABLE SYS_HELP_FILE_INFO IS '帮助文档信息表';

CREATE TABLE SYS_MIGRATE_INFO(
    MIG_ID VARCHAR(50)  NOT NULL,
    MIG_TAB_NAME VARCHAR(50) ,
    MIG_TAB_CNAME VARCHAR(200) ,
    MIG_TYPE CHAR(1),
    MIG_COL_ID  VARCHAR(50),
    MIG_COL_NAME  VARCHAR(200),
    PARENT_MIG_ID  VARCHAR(50),
    MIG_REL_ID  VARCHAR(50),
    MIG_REL_NAME  VARCHAR(200),
    MIG_REL_TYPE  CHAR(1),
    MIG_REL_VALUE  VARCHAR(50),
    MIG_END_SIGN  VARCHAR(50),
    MIG_CONVER_TYPE  CHAR(1),
    PRIMARY KEY (MIG_ID)
);
COMMENT ON TABLE SYS_MIGRATE_INFO IS '导入导出信息配置表';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_ID IS 'ID';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_TAB_NAME IS '表英文名';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_TAB_CNAME IS '表中文名';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_TYPE IS '表类型';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_COL_ID IS '主键字段';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_COL_NAME IS '主键字段中文名';
COMMENT ON COLUMN SYS_MIGRATE_INFO.PARENT_MIG_ID IS '父级ID';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_REL_ID IS '关联表关联字段';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_REL_NAME IS '关联表-关联字段名称';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_REL_TYPE IS '关联表-关联字段解析类型';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_REL_VALUE IS '关联表-关联字段提取值';
COMMENT ON COLUMN SYS_MIGRATE_INFO.MIG_END_SIGN IS '自关联结束标识';
COMMENT ON TABLE SYS_MIGRATE_INFO IS '导入导出信息配置表';

CREATE TABLE SYS_MESSAGE_INFO(
    MESSAGE_ID VARCHAR(50) NOT NULL,
    MESSAGE_TYPE VARCHAR(1),
    MESSAGE_STATUS VARCHAR(1),
    MESSAGE_TITLE VARCHAR(50),
    MESSAGE_CONTENT VARCHAR(500),
    MESSAGE_REV_USER VARCHAR(500),
    DEL_FLAG VARCHAR(1),
    APP_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (MESSAGE_ID)
);
COMMENT ON TABLE SYS_MESSAGE_INFO IS '用户消息信息表';
COMMENT ON COLUMN SYS_MESSAGE_INFO.MESSAGE_ID IS '消息ID';
COMMENT ON COLUMN SYS_MESSAGE_INFO.MESSAGE_TYPE IS '消息类型:1-提醒;2-通知';
COMMENT ON COLUMN SYS_MESSAGE_INFO.MESSAGE_STATUS IS '消息状态:0-未读;1-已读';
COMMENT ON COLUMN SYS_MESSAGE_INFO.MESSAGE_TITLE IS '消息标题';
COMMENT ON COLUMN SYS_MESSAGE_INFO.MESSAGE_CONTENT IS '消息内容';
COMMENT ON COLUMN SYS_MESSAGE_INFO.MESSAGE_REV_USER IS '消息接收用户';
COMMENT ON COLUMN SYS_MESSAGE_INFO.DEL_FLAG IS '删除标记';
COMMENT ON COLUMN SYS_MESSAGE_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_MESSAGE_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_MESSAGE_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_MESSAGE_INFO IS '用户消息信息表';

CREATE TABLE SYS_STATISTICAL_STRATEGY(
    STRATEGY_ID  VARCHAR(50) NOT NULL,
    SERVICE_URL  VARCHAR(200),
    FUNCTION_NAME  VARCHAR(50),
    REPEAT_FLAG  CHAR(1),
    CONFIG_STATUS  CHAR(1),
    DEL_FLAG  CHAR(1),
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (STRATEGY_ID)
);
COMMENT ON TABLE SYS_STATISTICAL_STRATEGY IS '统计策略表';
COMMENT ON COLUMN SYS_STATISTICAL_STRATEGY.STRATEGY_ID IS '策略ID';
COMMENT ON COLUMN SYS_STATISTICAL_STRATEGY.SERVICE_URL IS '服务地址';
COMMENT ON COLUMN SYS_STATISTICAL_STRATEGY.FUNCTION_NAME IS '功能名称';
COMMENT ON COLUMN SYS_STATISTICAL_STRATEGY.REPEAT_FLAG IS '是否重复计数,0-否;1-是';
COMMENT ON COLUMN SYS_STATISTICAL_STRATEGY.CONFIG_STATUS IS '策略状态,0-停用;1-启用';
COMMENT ON COLUMN SYS_STATISTICAL_STRATEGY.DEL_FLAG IS '删除标记';
COMMENT ON COLUMN SYS_STATISTICAL_STRATEGY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_STATISTICAL_STRATEGY.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_STATISTICAL_STRATEGY IS '统计策略表';

CREATE TABLE SYS_STATISTICAL_INFO(
    STATISTICAL_ID VARCHAR(50)  NOT NULL,
    STRATEGY_ID VARCHAR(50)  NOT NULL,
    REQUEST_URL  VARCHAR(200),
    REQUEST_USER_ID  VARCHAR(200),
    REQUEST_HOST  VARCHAR(50),
    USER_AGENT  VARCHAR(500),
    REQUEST_METHOD  VARCHAR(20),
    REQUEST_TIME  VARCHAR(50),
    RESPONSE_STATUS  VARCHAR(10),
    RESPONSE_DATA_SIZE  INTEGER,
    PRIMARY KEY (STATISTICAL_ID)
);
COMMENT ON TABLE SYS_STATISTICAL_INFO IS '统计信息表';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.STATISTICAL_ID IS '统计ID';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.STRATEGY_ID IS '统计策略ID';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.REQUEST_URL IS '请求地址';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.REQUEST_USER_ID IS '请求用户ID';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.REQUEST_HOST IS '请求主机IP';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.USER_AGENT IS '用户代理';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.REQUEST_METHOD IS '请求方式';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.REQUEST_TIME IS '请求时间';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.RESPONSE_STATUS IS '响应状态码';
COMMENT ON COLUMN SYS_STATISTICAL_INFO.RESPONSE_DATA_SIZE IS '响应数据大小';
COMMENT ON TABLE SYS_STATISTICAL_INFO IS '统计信息表';

CREATE TABLE SYS_PARAM_INFO(
    PARAM_ID VARCHAR(50) NOT NULL,
    PARAM_NAME VARCHAR(200),
    PARAM_VALUE VARCHAR(200),
    PARAM_RMK VARCHAR(300),
    APP_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (PARAM_ID)
);
COMMENT ON TABLE SYS_PARAM_INFO IS '参数信息表';
COMMENT ON COLUMN SYS_PARAM_INFO.PARAM_ID IS '参数ID';
COMMENT ON COLUMN SYS_PARAM_INFO.PARAM_NAME IS '参数名称';
COMMENT ON COLUMN SYS_PARAM_INFO.PARAM_VALUE IS '参数值';
COMMENT ON COLUMN SYS_PARAM_INFO.PARAM_RMK IS '参数描述';
COMMENT ON COLUMN SYS_PARAM_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_PARAM_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_PARAM_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_PARAM_INFO IS '参数信息表';

CREATE TABLE SYS_APP_INFO(
    APP_ID VARCHAR(50) NOT NULL,
    APP_NAME VARCHAR(200),
    APP_ORDER INTEGER,
    APP_LOGO VARCHAR(300),
    BROWSER_TITLE VARCHAR(100),
    APP_URL VARCHAR(500),
    APP_RMK VARCHAR(500),
    APP_REL VARCHAR(50),
    APP_STATE CHAR(1),
    PRIMARY KEY (APP_ID)
);
COMMENT ON TABLE SYS_APP_INFO IS '租户信息表';
COMMENT ON COLUMN SYS_APP_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_APP_INFO.APP_NAME IS '租户名称';
COMMENT ON COLUMN SYS_APP_INFO.APP_ORDER IS '租户排序';
COMMENT ON COLUMN SYS_APP_INFO.APP_LOGO IS '租户LOGO路径';
COMMENT ON COLUMN SYS_APP_INFO.BROWSER_TITLE IS '浏览器标题';
COMMENT ON COLUMN SYS_APP_INFO.APP_URL IS '租户地址';
COMMENT ON COLUMN SYS_APP_INFO.APP_RMK IS '租户描述';
COMMENT ON COLUMN SYS_APP_INFO.APP_REL IS '关联租户';
COMMENT ON COLUMN SYS_APP_INFO.APP_STATE IS '租户状态';
COMMENT ON TABLE SYS_APP_INFO IS '租户信息表';

CREATE TABLE SYS_USER_APP_REL(
    USER_ID VARCHAR(50) NOT NULL,
    APP_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (USER_ID,APP_ID)
);
COMMENT ON TABLE SYS_USER_APP_REL IS '租户用户权限表';
COMMENT ON COLUMN SYS_USER_APP_REL.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER_APP_REL.APP_ID IS '租户ID';
COMMENT ON TABLE SYS_USER_APP_REL IS '租户用户权限表';

CREATE TABLE SYS_COLLECT_INFO(
    COLLECT_ID VARCHAR(50) NOT NULL,
    COLLECT_NAME VARCHAR(200)  NOT NULL,
    COLLECT_OBJ VARCHAR(50) NOT NULL,
    COLLECT_TYPE INTEGER NOT NULL,
    APP_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    PARENT_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP ,
    MODIFY_TIME TIMESTAMP ,
    COLLECT_RMK VARCHAR(500),
    COLLECT_ICON VARCHAR(100) NOT NULL,
    COLLECT_URL VARCHAR(500) NOT NULL,
    PRIMARY KEY (COLLECT_ID)
);
COMMENT ON TABLE SYS_COLLECT_INFO IS '收藏信息表';
COMMENT ON COLUMN SYS_COLLECT_INFO.COLLECT_ID IS '收藏项ID';
COMMENT ON COLUMN SYS_COLLECT_INFO.COLLECT_NAME IS '收藏项名称';
COMMENT ON COLUMN SYS_COLLECT_INFO.COLLECT_OBJ IS '收藏项目标ID';
COMMENT ON COLUMN SYS_COLLECT_INFO.COLLECT_TYPE IS '收藏项目标类型';
COMMENT ON COLUMN SYS_COLLECT_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_COLLECT_INFO.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_COLLECT_INFO.PARENT_ID IS '父ID';
COMMENT ON COLUMN SYS_COLLECT_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_COLLECT_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SYS_COLLECT_INFO.COLLECT_RMK IS '收藏项描述';
COMMENT ON TABLE SYS_COLLECT_INFO IS '收藏信息表';

CREATE TABLE SYS_MENU_TMP(
    MENU_ID         	VARCHAR(50) 	NOT NULL,
	MENU_NAME       	VARCHAR(100) 	NOT NULL,
	MENU_ROUTE_NAME     VARCHAR(100),
	MENU_TYPE       	VARCHAR(1) 		NOT NULL,
	MENU_URL        	VARCHAR(500),
	HTTP_METHOD     	VARCHAR(20),
	MENU_PATH       	VARCHAR(300),
	BUTTON_PERMISSION 	VARCHAR(100),
	MENU_COLOR      	VARCHAR(50),
	PARENT_ID  			VARCHAR(50)     NOT NULL,
	MENU_ICON       	VARCHAR(50),
	COMPONENT_PATH  	VARCHAR(300),
	MENU_SORT       	INTEGER,
	CREATE_TIME			TIMESTAMP  		NOT NULL,
	MODIFY_TIME			TIMESTAMP ,
	DEL_FLAG   			VARCHAR(1) ,
	APP_ID 				VARCHAR(50),
	AUTH_FLAG 			CHAR(1),
	HIDE_FLAG 			CHAR(1),
	ALIVE_FLAG 			CHAR(1),
    PRIMARY KEY (MENU_ID)
);
COMMENT ON TABLE SYS_MENU_TMP IS '菜单表';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_ID IS '主键';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_NAME IS '菜单名称';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_ROUTE_NAME IS '菜单路径名称,用于多语言标识';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_TYPE IS '菜单类型 0-菜单 1-按钮';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_URL IS '后台请求URL';
COMMENT ON COLUMN SYS_MENU_TMP.HTTP_METHOD IS '请求方式';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_PATH IS '前端URL';
COMMENT ON COLUMN SYS_MENU_TMP.BUTTON_PERMISSION IS '按钮权限资源标识';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_COLOR IS '颜色';
COMMENT ON COLUMN SYS_MENU_TMP.PARENT_ID IS '父资源ID';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_ICON IS '图标';
COMMENT ON COLUMN SYS_MENU_TMP.COMPONENT_PATH IS '组件路径';
COMMENT ON COLUMN SYS_MENU_TMP.MENU_SORT IS '排序权重';
COMMENT ON COLUMN SYS_MENU_TMP.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_MENU_TMP.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SYS_MENU_TMP.DEL_FLAG IS '是否删除 1-删除，0-未删除';
COMMENT ON COLUMN SYS_MENU_TMP.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_MENU_TMP.AUTH_FLAG IS '权限标识:0-不需要权限;1-需要权限';
COMMENT ON COLUMN SYS_MENU_TMP.HIDE_FLAG IS '隐藏菜单：0-否;1-是';
COMMENT ON COLUMN SYS_MENU_TMP.ALIVE_FLAG IS '缓存组件：0-否;1-是';
COMMENT ON TABLE SYS_MENU_TMP IS '菜单模板表';

CREATE TABLE NOTICE_SMS_SEND_LOG(
    LOG_ID VARCHAR(50)  NOT NULL,
    SRV_ID VARCHAR(50)  NOT NULL,
    SMS_SEND_TIME VARCHAR(50)  NOT NULL,
    SMS_SEND_USER VARCHAR(50)  NOT NULL,
    SMS_RECEIVE_USER VARCHAR(2000)  NOT NULL,
    SEND_CONTENT  VARCHAR(500),
    SEND_STATUS  CHAR(6),
    PRIMARY KEY (LOG_ID)
);
COMMENT ON TABLE NOTICE_SMS_SEND_LOG IS '短信服务器发送日志表 ';
COMMENT ON COLUMN NOTICE_SMS_SEND_LOG.LOG_ID IS '主键';
COMMENT ON COLUMN NOTICE_SMS_SEND_LOG.SRV_ID IS '服务器ID';
COMMENT ON COLUMN NOTICE_SMS_SEND_LOG.SMS_SEND_TIME IS '发送时间';
COMMENT ON COLUMN NOTICE_SMS_SEND_LOG.SMS_SEND_USER IS '发送用户';
COMMENT ON COLUMN NOTICE_SMS_SEND_LOG.SMS_RECEIVE_USER IS '所有接收者';
COMMENT ON COLUMN NOTICE_SMS_SEND_LOG.SEND_CONTENT IS '发送内容';
COMMENT ON COLUMN NOTICE_SMS_SEND_LOG.SEND_STATUS IS '发送状态';
COMMENT ON TABLE NOTICE_SMS_SEND_LOG IS '短信服务器发送日志表 ';

CREATE TABLE NOTICE_SMS_SRV_INFO(
    SRV_ID VARCHAR(50) NOT NULL,
    SRV_NAME VARCHAR(200) NOT NULL,
    SRV_SMS_PROGRAM VARCHAR(200) NOT NULL,
    SRV_RMK VARCHAR(500),
    SRV_EXTEND_FIELD VARCHAR(1000),
    APP_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (SRV_ID)
);
COMMENT ON TABLE NOTICE_SMS_SRV_INFO IS '短信服务器信息表 ';
COMMENT ON COLUMN NOTICE_SMS_SRV_INFO.SRV_ID IS '主键';
COMMENT ON COLUMN NOTICE_SMS_SRV_INFO.SRV_NAME IS '服务器名称';
COMMENT ON COLUMN NOTICE_SMS_SRV_INFO.SRV_SMS_PROGRAM IS '短信发送接口实现类';
COMMENT ON COLUMN NOTICE_SMS_SRV_INFO.SRV_RMK IS '服务器描述';
COMMENT ON COLUMN NOTICE_SMS_SRV_INFO.SRV_EXTEND_FIELD IS '服务器扩展属性';
COMMENT ON COLUMN NOTICE_SMS_SRV_INFO.APP_ID IS '租户ID';
COMMENT ON TABLE NOTICE_SMS_SRV_INFO IS '短信服务器信息表 ';

CREATE TABLE NOTICE_SMS_TEMP_INFO(
    TEMP_ID  VARCHAR(50) NOT NULL,
    EXT_ATTR1  VARCHAR(100),
    EXT_ATTR2  VARCHAR(200),
    EXT_ATTR3  VARCHAR(1000),
    TEMP_HTML  CLOB(2000000000),
    TEMP_NAME  VARCHAR(200),
    TEMP_RMK  VARCHAR(500),
    TEMP_USER  VARCHAR(50),
    APP_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (TEMP_ID)
);
COMMENT ON TABLE NOTICE_SMS_TEMP_INFO IS '短信模板信息表 ';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.TEMP_ID IS '主键';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.EXT_ATTR1 IS '扩展属性1';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.EXT_ATTR2 IS '扩展属性2';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.EXT_ATTR3 IS '扩展属性3';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.TEMP_HTML IS '短信模板内容';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.TEMP_NAME IS '短信模板名称';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.TEMP_RMK IS '短信模板描述';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.TEMP_USER IS '创建用户';
COMMENT ON COLUMN NOTICE_SMS_TEMP_INFO.APP_ID IS '租户ID';
COMMENT ON TABLE NOTICE_SMS_TEMP_INFO IS '短信模板信息表 ';

CREATE TABLE NOTICE_SYSTEM_MESSAGE(
    MSG_ID VARCHAR(50)  NOT NULL,
    RECEIVE_USER VARCHAR(50)  NOT NULL,
    SEND_USER VARCHAR(50)  NOT NULL,
    SEND_TIME VARCHAR(50)  NOT NULL,
    READ_FLAG  VARCHAR(6) NOT NULL,
    MSG_CONTENT VARCHAR(2000),
    MSG_THEME VARCHAR(200),
    PRIMARY KEY (MSG_ID)
);
COMMENT ON TABLE NOTICE_SYSTEM_MESSAGE IS '系统消息表 ';
COMMENT ON COLUMN NOTICE_SYSTEM_MESSAGE.MSG_ID IS '主键';
COMMENT ON COLUMN NOTICE_SYSTEM_MESSAGE.RECEIVE_USER IS '消息接收者';
COMMENT ON COLUMN NOTICE_SYSTEM_MESSAGE.SEND_USER IS '消息发送者';
COMMENT ON COLUMN NOTICE_SYSTEM_MESSAGE.SEND_TIME IS '消息发送时间';
COMMENT ON COLUMN NOTICE_SYSTEM_MESSAGE.READ_FLAG IS '消息是否已读状态';
COMMENT ON COLUMN NOTICE_SYSTEM_MESSAGE.MSG_CONTENT IS '消息内容';
COMMENT ON COLUMN NOTICE_SYSTEM_MESSAGE.MSG_THEME IS '消息主题';
COMMENT ON TABLE NOTICE_SYSTEM_MESSAGE IS '系统消息表 ';

CREATE TABLE KNOW_KNOWLEDGE_ATTACH_INFO(
    ATT_ID VARCHAR(50)  NOT NULL,
    KNOWLEDGE_ID VARCHAR(50) NOT NULL,
    APP_ID VARCHAR(50) NOT NULL,
    ATT_NAME VARCHAR(200) NOT NULL,
    ATT_CONTENT BLOB(16777215) NOT NULL,
    CREATE_TIME TIMESTAMP ,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (ATT_ID)
);
COMMENT ON TABLE KNOW_KNOWLEDGE_ATTACH_INFO IS '知识库附件信息表';
COMMENT ON COLUMN KNOW_KNOWLEDGE_ATTACH_INFO.ATT_ID IS '附件id';
COMMENT ON COLUMN KNOW_KNOWLEDGE_ATTACH_INFO.KNOWLEDGE_ID IS '知识库id';
COMMENT ON COLUMN KNOW_KNOWLEDGE_ATTACH_INFO.APP_ID IS '租户id';
COMMENT ON COLUMN KNOW_KNOWLEDGE_ATTACH_INFO.ATT_NAME IS '附件名称';
COMMENT ON COLUMN KNOW_KNOWLEDGE_ATTACH_INFO.ATT_CONTENT IS '附件内容';
COMMENT ON COLUMN KNOW_KNOWLEDGE_ATTACH_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN KNOW_KNOWLEDGE_ATTACH_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE KNOW_KNOWLEDGE_ATTACH_INFO IS '知识库附件信息表';

CREATE TABLE KNOW_KNOWLEDGE_DIR_INFO(
    DIR_ID VARCHAR(50) NOT NULL,
    DIR_NAME VARCHAR(200),
    PARENT_ID VARCHAR(50),
    DIR_RMK VARCHAR(500),
    APP_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP ,
    MODIFY_TIME TIMESTAMP ,
    DIR_ORDER INTEGER,
    PRIMARY KEY (DIR_ID)
);
COMMENT ON TABLE KNOW_KNOWLEDGE_DIR_INFO IS '知识分类表';
COMMENT ON COLUMN KNOW_KNOWLEDGE_DIR_INFO.DIR_ID IS '分类ID';
COMMENT ON COLUMN KNOW_KNOWLEDGE_DIR_INFO.DIR_NAME IS '分类名称';
COMMENT ON COLUMN KNOW_KNOWLEDGE_DIR_INFO.PARENT_ID IS '父ID';
COMMENT ON COLUMN KNOW_KNOWLEDGE_DIR_INFO.DIR_RMK IS '分类描述';
COMMENT ON COLUMN KNOW_KNOWLEDGE_DIR_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN KNOW_KNOWLEDGE_DIR_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN KNOW_KNOWLEDGE_DIR_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN KNOW_KNOWLEDGE_DIR_INFO.DIR_ORDER IS '排序';
COMMENT ON TABLE KNOW_KNOWLEDGE_DIR_INFO IS '知识分类表';

CREATE TABLE KNOW_KNOWLEDGE_INFO(
    KNOWLEDGE_ID VARCHAR(50) NOT NULL,
    KNOWLEDGE_TITLE VARCHAR(200),
    KNOWLEDGE_RMK VARCHAR(500),
    KEY_WORDS VARCHAR(500),
    KNOWLEDGE_STATUS CHAR(1),
    CREATE_USER VARCHAR(50),
    MODIFY_USER VARCHAR(50),
    CREATE_TIME TIMESTAMP ,
    MODIFY_TIME TIMESTAMP ,
    KNOWLEDGE_CONTENT VARCHAR(50) NOT NULL,
    DIR_ID VARCHAR(50),
    APP_ID VARCHAR(50) NOT NULL,
    KNOWLEDGE_CONTENT_EDIT_TYPE CHAR(1),
    PRIMARY KEY (KNOWLEDGE_ID)
);
COMMENT ON TABLE KNOW_KNOWLEDGE_INFO IS '知识库表';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.KNOWLEDGE_ID IS '知识ID';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.KNOWLEDGE_TITLE IS '知识标题';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.KNOWLEDGE_RMK IS '知识描述';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.KEY_WORDS IS '关键词';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.KNOWLEDGE_STATUS IS '知识状态';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.CREATE_USER IS '创建用户';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.MODIFY_USER IS '修改用户';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.KNOWLEDGE_CONTENT IS '知识内容';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.DIR_ID IS '分类ID';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN KNOW_KNOWLEDGE_INFO.KNOWLEDGE_CONTENT_EDIT_TYPE IS '知识内容类型';
COMMENT ON TABLE KNOW_KNOWLEDGE_INFO IS '知识库表';

CREATE TABLE SYS_USER_COMMENT_INFO(
    COMMENT_ID 	VARCHAR(50) NOT NULL,
    COMMENT_CONTENT CLOB(65535),
    COMMENT_OBJID	VARCHAR(50)  NOT NULL,
    CREATE_USER	VARCHAR(50)  NOT NULL,
    APP_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP ,
    PRIMARY KEY (COMMENT_ID)
);
COMMENT ON TABLE SYS_USER_COMMENT_INFO IS '用户评论信息表';
COMMENT ON COLUMN SYS_USER_COMMENT_INFO.COMMENT_ID IS '评论id';
COMMENT ON COLUMN SYS_USER_COMMENT_INFO.COMMENT_CONTENT IS '评论内容';
COMMENT ON COLUMN SYS_USER_COMMENT_INFO.COMMENT_OBJID IS '评论对象ID';
COMMENT ON COLUMN SYS_USER_COMMENT_INFO.CREATE_USER IS '创建用户';
COMMENT ON COLUMN SYS_USER_COMMENT_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_USER_COMMENT_INFO.CREATE_TIME IS '创建时间';
COMMENT ON TABLE SYS_USER_COMMENT_INFO IS '用户评论信息表';

CREATE TABLE SYS_WORKFLOW_TYPE_INFO(
    TYPE_ID VARCHAR(50)  NOT NULL,
    TYPE_NAME  VARCHAR(100),
    TYPE_RMK  VARCHAR(300),
    TYPE_ORDER INTEGER,
    APP_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (TYPE_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_TYPE_INFO IS '工作流类型信息 ';
COMMENT ON COLUMN SYS_WORKFLOW_TYPE_INFO.TYPE_ID IS '工作流类型ID';
COMMENT ON COLUMN SYS_WORKFLOW_TYPE_INFO.TYPE_NAME IS '工作流类型名称';
COMMENT ON COLUMN SYS_WORKFLOW_TYPE_INFO.TYPE_RMK IS '工作流类型描述';
COMMENT ON COLUMN SYS_WORKFLOW_TYPE_INFO.TYPE_ORDER IS '工作流类型排序';
COMMENT ON COLUMN SYS_WORKFLOW_TYPE_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_WORKFLOW_TYPE_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_WORKFLOW_TYPE_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_WORKFLOW_TYPE_INFO IS '工作流类型信息 ';

CREATE TABLE SYS_WORKFLOW_INFO(
    WORKFLOW_ID VARCHAR(50) NOT NULL,
    WORKFLOW_CODE VARCHAR(100) NOT NULL,
    WORKFLOW_NAME VARCHAR(100),
    VERSION_NUM VARCHAR(10),
    VERSION_MAX VARCHAR(1),
    WORKFLOW_RMK VARCHAR(300),
    WORKFLOW_LEVEL INTEGER,
    TYPE_ID VARCHAR(50) NOT NULL,
    WF_ID VARCHAR(100),
    DETAIL_URL VARCHAR(1000),
    FINISH_SERVICE VARCHAR(1000),
    APP_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (WORKFLOW_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_INFO IS '工作流定义信息 ';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.WORKFLOW_ID IS '工作流ID';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.WORKFLOW_CODE IS '工作流标识';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.WORKFLOW_NAME IS '工作流名称';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.VERSION_NUM IS '工作流版本';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.VERSION_MAX IS '最大版本标志';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.WORKFLOW_RMK IS '工作流描述';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.WORKFLOW_LEVEL IS '工作流级别';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.TYPE_ID IS '工作流类型ID';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.WF_ID IS '流程平台ID';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.DETAIL_URL IS '详情获取地址';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.FINISH_SERVICE IS '结束回调服务';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_WORKFLOW_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_WORKFLOW_INFO IS '工作流定义信息 ';

CREATE TABLE SYS_WORKFLOW_NODE_INFO(
    NODE_ID VARCHAR(50)  NOT NULL,
    NODE_NAME  VARCHAR(100),
    PARENT_IDS  VARCHAR(1000),
    NODE_LEVEL INTEGER,
    WORKFLOW_ID  VARCHAR(50),
    NODE_RMK  VARCHAR(300),
    AGREE_NUM INTEGER,
    DISAGREE_NUM INTEGER,
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (NODE_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_NODE_INFO IS '工作流节点信息 ';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.NODE_ID IS '节点ID';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.NODE_NAME IS '节点名称';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.PARENT_IDS IS '多上级节点ID';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.NODE_LEVEL IS '节点层级';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.WORKFLOW_ID IS '工作流ID';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.NODE_RMK IS '节点说明';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.AGREE_NUM IS '通过人数 0-所有人通过、N-n个人通过';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.DISAGREE_NUM IS '不通过人数 0-所有人不通过、N-n个人不通过';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_WORKFLOW_NODE_INFO IS '工作流节点信息 ';

CREATE TABLE SYS_WORKFLOW_NODE_AUTH(
    AUTH_ID VARCHAR(50)  NOT NULL,
    AUTH_TYPE  VARCHAR(10),
    OBJ_ID  VARCHAR(50),
    NODE_ID  VARCHAR(50),
    CREATE_TIME TIMESTAMP  NOT NULL,
    PRIMARY KEY (AUTH_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_NODE_AUTH IS '工作流节点权限 ';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_AUTH.AUTH_ID IS '权限ID';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_AUTH.AUTH_TYPE IS '权限类型 role-角色，user-用户';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_AUTH.OBJ_ID IS '对象ID';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_AUTH.NODE_ID IS '节点ID';
COMMENT ON COLUMN SYS_WORKFLOW_NODE_AUTH.CREATE_TIME IS '创建时间';
COMMENT ON TABLE SYS_WORKFLOW_NODE_AUTH IS '工作流节点权限 ';

CREATE TABLE SYS_WORKFLOW_MACRO_INFO(
    MACRO_ID VARCHAR(50) NOT NULL,
    MACRO_CODE VARCHAR(100) NOT NULL,
    MACRO_NAME VARCHAR(100) NOT NULL,
    MACRO_TYPE VARCHAR(10) NOT NULL,
    WORKFLOW_ID VARCHAR(50) NOT NULL,
    MACRO_RMK VARCHAR(300),
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (MACRO_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_MACRO_INFO IS '工作流宏变量信息 ';
COMMENT ON COLUMN SYS_WORKFLOW_MACRO_INFO.MACRO_ID IS '宏变量ID';
COMMENT ON COLUMN SYS_WORKFLOW_MACRO_INFO.MACRO_CODE IS '宏变量标识';
COMMENT ON COLUMN SYS_WORKFLOW_MACRO_INFO.MACRO_NAME IS '宏变量名称';
COMMENT ON COLUMN SYS_WORKFLOW_MACRO_INFO.MACRO_TYPE IS '宏变量类型 workflow/instance/node/auth-role/auth-user';
COMMENT ON COLUMN SYS_WORKFLOW_MACRO_INFO.WORKFLOW_ID IS '工作流ID';
COMMENT ON COLUMN SYS_WORKFLOW_MACRO_INFO.MACRO_RMK IS '宏变量说明';
COMMENT ON COLUMN SYS_WORKFLOW_MACRO_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_WORKFLOW_MACRO_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_WORKFLOW_MACRO_INFO IS '工作流宏变量信息 ';

CREATE TABLE SYS_WORKFLOW_INSTANCE(
    INSTANCE_ID  VARCHAR(50) NOT NULL,
    WORKFLOW_ID  VARCHAR(50),
    INSTANCE_NAME  VARCHAR(30),
    INSTANCE_RMK  VARCHAR(4000),
    INSTANCE_STATUS  VARCHAR(1),
    CREATE_USER  VARCHAR(50),
    APP_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (INSTANCE_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_INSTANCE IS '工作流实例信息 ';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.INSTANCE_ID IS '实例ID';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.WORKFLOW_ID IS '工作流ID';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.INSTANCE_NAME IS '实例名称';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.INSTANCE_RMK IS '实例说明';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.INSTANCE_STATUS IS '实例状态 0-未处理 1-处理中 2-已完成';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.CREATE_USER IS '创建用户';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_WORKFLOW_INSTANCE.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_WORKFLOW_INSTANCE IS '工作流实例信息 ';

CREATE TABLE SYS_WORKFLOW_INST_NODE(
    INODE_ID VARCHAR(50)  NOT NULL,
    NODE_ID VARCHAR(50)  NOT NULL,
    INSTANCE_ID  VARCHAR(50),
    NODE_STATUS CHAR(1),
    ACTIVE_FLAG CHAR(1),
    PRIMARY KEY (INODE_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_INST_NODE IS '工作流实例节点信息 ';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE.INODE_ID IS '实例节点ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE.NODE_ID IS '流程节点ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE.INSTANCE_ID IS '实例ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE.NODE_STATUS IS '节点状态 0-未处理 1-通过 2-未通过 3-部分通过';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE.ACTIVE_FLAG IS '当前节点';
COMMENT ON TABLE SYS_WORKFLOW_INST_NODE IS '工作流实例节点信息 ';

CREATE TABLE SYS_WORKFLOW_INST_NODE_AUTH(
    AUTH_ID VARCHAR(50)  NOT NULL,
    AUTH_TYPE VARCHAR(10),
    OBJ_ID VARCHAR(50),
    INODE_ID VARCHAR(50),
    CREATE_TIME TIMESTAMP  NOT NULL,
    PRIMARY KEY (AUTH_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_INST_NODE_AUTH IS '工作流实例节点权限 ';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_AUTH.AUTH_ID IS '流程权限ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_AUTH.AUTH_TYPE IS '权限类型 role-角色，user-用户';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_AUTH.OBJ_ID IS '对象ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_AUTH.INODE_ID IS '实例节点ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_AUTH.CREATE_TIME IS '创建时间';
COMMENT ON TABLE SYS_WORKFLOW_INST_NODE_AUTH IS '工作流实例节点权限 ';

CREATE TABLE SYS_WORKFLOW_INST_NODE_OPER(
    OPER_ID  VARCHAR(50) NOT NULL,
    LOGIN_NAME  VARCHAR(50),
    AGREE_FLAG  VARCHAR(1),
    OPER_RMK  VARCHAR(500),
    INODE_ID  VARCHAR(50),
    INSTANCE_ID  VARCHAR(50),
    OPER_TIME  VARCHAR(50) NOT NULL,
    PRIMARY KEY (OPER_ID)
);
COMMENT ON TABLE SYS_WORKFLOW_INST_NODE_OPER IS '工作流实例节点审批 ';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_OPER.OPER_ID IS '操作ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_OPER.LOGIN_NAME IS '操作用户';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_OPER.AGREE_FLAG IS '是否同意 1-同意 0-不同意';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_OPER.OPER_RMK IS '处理意见';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_OPER.INODE_ID IS '节点ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_OPER.INSTANCE_ID IS '实例ID';
COMMENT ON COLUMN SYS_WORKFLOW_INST_NODE_OPER.OPER_TIME IS '创建时间';
COMMENT ON TABLE SYS_WORKFLOW_INST_NODE_OPER IS '工作流实例节点审批 ';

CREATE TABLE SYS_DICT_ITEM(
    ID VARCHAR(50)  NOT NULL,
    DICT_ID  VARCHAR(50),
    ITEM_TEXT  VARCHAR(100),
    ITEM_VALUE  VARCHAR(100),
    DESCRIPTION  VARCHAR(255),
    SORT_ORDER  INTEGER,
    STATUS INTEGER,
    CREATE_TIME TIMESTAMP  NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON TABLE SYS_DICT_ITEM IS '字典明细表';
COMMENT ON COLUMN SYS_DICT_ITEM.DICT_ID IS '字典ID';
COMMENT ON COLUMN SYS_DICT_ITEM.ITEM_TEXT IS '字典项文本';
COMMENT ON COLUMN SYS_DICT_ITEM.ITEM_VALUE IS '字典项值';
COMMENT ON COLUMN SYS_DICT_ITEM.DESCRIPTION IS '描述';
COMMENT ON COLUMN SYS_DICT_ITEM.SORT_ORDER IS '排序';
COMMENT ON COLUMN SYS_DICT_ITEM.STATUS IS '状态（1启用 0不启用）';
COMMENT ON COLUMN SYS_DICT_ITEM.CREATE_TIME IS '创建时间';
COMMENT ON TABLE SYS_DICT_ITEM IS '字典明细表';

CREATE TABLE SYS_DICT(
    ID VARCHAR(50)  NOT NULL,
    DICT_NAME VARCHAR(100) ,
    DICT_CODE VARCHAR(100) ,
    DESCRIPTION VARCHAR(255) ,
    DEL_FLAG INTEGER ,
    CREATE_TIME TIMESTAMP  NOT NULL,
    TYPE  VARCHAR(255),
    PRIMARY KEY (ID)
);
COMMENT ON TABLE SYS_DICT IS '字典表';
COMMENT ON COLUMN SYS_DICT.DICT_NAME IS '字典名称';
COMMENT ON COLUMN SYS_DICT.DICT_CODE IS '字典编码';
COMMENT ON COLUMN SYS_DICT.DESCRIPTION IS '描述';
COMMENT ON COLUMN SYS_DICT.DEL_FLAG IS '删除状态(1，不删，0，删除)';
COMMENT ON COLUMN SYS_DICT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_DICT.TYPE IS '字典类型';
COMMENT ON TABLE SYS_DICT IS '字典表';

CREATE TABLE SYS_USER_TASK_EXT(
    EXT_ID VARCHAR(50) NOT NULL,
    EXT_NAME VARCHAR(200),
    UNDO_SQL CLOB(65535),
    DONE_SQL CLOB(65535),
    EXT_URL VARCHAR(500),
    EXT_RMK VARCHAR(500),
    APP_ID VARCHAR(50) NOT NULL,
    CREATE_TIME TIMESTAMP  NOT NULL,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (EXT_ID)
);
COMMENT ON TABLE SYS_USER_TASK_EXT IS '用户任务扩展表 ';
COMMENT ON COLUMN SYS_USER_TASK_EXT.EXT_ID IS '任务扩展ID';
COMMENT ON COLUMN SYS_USER_TASK_EXT.EXT_NAME IS '任务扩展名称';
COMMENT ON COLUMN SYS_USER_TASK_EXT.UNDO_SQL IS '待处理任务SQL';
COMMENT ON COLUMN SYS_USER_TASK_EXT.DONE_SQL IS '已处理任务SQL';
COMMENT ON COLUMN SYS_USER_TASK_EXT.EXT_URL IS '任务扩展URL';
COMMENT ON COLUMN SYS_USER_TASK_EXT.EXT_RMK IS '任务扩展描述';
COMMENT ON COLUMN SYS_USER_TASK_EXT.APP_ID IS '租户ID';
COMMENT ON COLUMN SYS_USER_TASK_EXT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_USER_TASK_EXT.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_USER_TASK_EXT IS '用户任务扩展表 ';

CREATE TABLE NOTICE_BUS_REL(
    SRV_ID VARCHAR(50),
    BUS_ID VARCHAR(50)  NOT NULL,
    SRV_TYPE VARCHAR(6)  NOT NULL,
    SRV_OPTIONS  VARCHAR(300),
    PRIMARY KEY (BUS_ID,SRV_TYPE)
);
COMMENT ON TABLE NOTICE_BUS_REL IS '通知方式与业务数据关系表 ';
COMMENT ON COLUMN NOTICE_BUS_REL.SRV_ID IS '服务器ID';
COMMENT ON COLUMN NOTICE_BUS_REL.BUS_ID IS '业务数据ID';
COMMENT ON COLUMN NOTICE_BUS_REL.SRV_TYPE IS '服务器类型';
COMMENT ON COLUMN NOTICE_BUS_REL.SRV_OPTIONS IS '服务器属性内容';
COMMENT ON TABLE NOTICE_BUS_REL IS '通知方式与业务数据关系表 ';

CREATE TABLE SYS_LAYOUT_INFO(
    LAY_ID VARCHAR(50) NOT NULL,
    LAY_NAME VARCHAR(200) NOT NULL,
    APP_ID VARCHAR(50) NOT NULL,
    LAY_TYPE VARCHAR(1),
    LAY_LEVEL INTEGER,
    LOGIN_NAME VARCHAR(50),
    LAY_RMK VARCHAR(50),
    CREATE_TIME TIMESTAMP ,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (LAY_ID)
);
COMMENT ON TABLE SYS_LAYOUT_INFO IS '布局信息表';
COMMENT ON COLUMN SYS_LAYOUT_INFO.LAY_ID IS '主键';
COMMENT ON COLUMN SYS_LAYOUT_INFO.LAY_NAME IS '布局名称';
COMMENT ON COLUMN SYS_LAYOUT_INFO.APP_ID IS '应用ID';
COMMENT ON COLUMN SYS_LAYOUT_INFO.LAY_TYPE IS '布局类型，0-默认布局；1-权限布局；2-自定义布局';
COMMENT ON COLUMN SYS_LAYOUT_INFO.LAY_LEVEL IS '应用ID';
COMMENT ON COLUMN SYS_LAYOUT_INFO.LOGIN_NAME IS '登录名';
COMMENT ON COLUMN SYS_LAYOUT_INFO.LAY_RMK IS '布局描述';
COMMENT ON COLUMN SYS_LAYOUT_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_LAYOUT_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_LAYOUT_INFO IS '布局信息表';

CREATE TABLE SYS_LAYOUT_ITEM_INFO(
    ITEM_ID VARCHAR(50) NOT NULL,
    ITEM_NAME VARCHAR(200) NOT NULL,
    APP_ID VARCHAR(50) NOT NULL,
    ITEM_COMP VARCHAR(400),
    MIN_WIDTH INTEGER,
    MIN_HEIGHT INTEGER,
    LOGIN_NAME VARCHAR(50),
    ITEM_ORDER INTEGER,
    ITEM_RMK VARCHAR(500),
    CREATE_TIME TIMESTAMP ,
    MODIFY_TIME TIMESTAMP ,
    PRIMARY KEY (ITEM_ID)
);
COMMENT ON TABLE SYS_LAYOUT_ITEM_INFO IS '布局数据项信息表';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.ITEM_ID IS '主键';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.ITEM_NAME IS '数据项名称';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.APP_ID IS '应用ID';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.ITEM_COMP IS '组件路径';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.MIN_WIDTH IS '最小宽度';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.MIN_HEIGHT IS '最小高度';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.LOGIN_NAME IS '登录名';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.ITEM_ORDER IS '数据项排序';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.ITEM_RMK IS '数据项描述';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_INFO.MODIFY_TIME IS '更新时间';
COMMENT ON TABLE SYS_LAYOUT_ITEM_INFO IS '布局数据项信息表';

CREATE TABLE SYS_LAYOUT_ITEM_REL(
    LAY_ID VARCHAR(50) NOT NULL,
    ITEM_ID VARCHAR(50) NOT NULL,
    REL_X INTEGER NOT NULL,
    REL_Y INTEGER NOT NULL,
    REL_W INTEGER NOT NULL,
    REL_H INTEGER NOT NULL,
    PRIMARY KEY (LAY_ID,ITEM_ID)
);
COMMENT ON TABLE SYS_LAYOUT_ITEM_REL IS '布局-数据项关系表';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_REL.LAY_ID IS '布局ID';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_REL.ITEM_ID IS '数据项ID';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_REL.REL_X IS '列编号';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_REL.REL_Y IS '行编号';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_REL.REL_W IS '初始宽度';
COMMENT ON COLUMN SYS_LAYOUT_ITEM_REL.REL_H IS '初始高度';
COMMENT ON TABLE SYS_LAYOUT_ITEM_REL IS '布局-数据项关系表';

CREATE TABLE SYS_ROLE_LAYOUT_ITEM_REL(
    ROLE_ID VARCHAR(50) NOT NULL,
    ITEM_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (ROLE_ID,ITEM_ID)
);
COMMENT ON TABLE SYS_ROLE_LAYOUT_ITEM_REL IS '角色-数据项权限表';
COMMENT ON COLUMN SYS_ROLE_LAYOUT_ITEM_REL.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE_LAYOUT_ITEM_REL.ITEM_ID IS '数据项ID';
COMMENT ON TABLE SYS_ROLE_LAYOUT_ITEM_REL IS '角色-数据项权限表';

CREATE TABLE SYS_ROLE_LAYOUT_REL(
    ROLE_ID VARCHAR(50) NOT NULL,
    LAY_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (ROLE_ID,LAY_ID)
);
COMMENT ON TABLE SYS_ROLE_LAYOUT_REL IS '角色-布局权限表';
COMMENT ON COLUMN SYS_ROLE_LAYOUT_REL.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE_LAYOUT_REL.LAY_ID IS '布局ID';
COMMENT ON TABLE SYS_ROLE_LAYOUT_REL IS '角色-布局权限表';

CREATE TABLE SYS_USER_PWD_LOG_INFO (
  LOG_ID VARCHAR(50),
  LOGIN_NAME VARCHAR(200),
  LOGIN_PWD VARCHAR(200),
  CREATE_TIME TIMESTAMP,
  PRIMARY KEY (LOG_ID)
);
COMMENT ON TABLE SYS_USER_PWD_LOG_INFO IS '角色-布局权限表';
COMMENT ON COLUMN SYS_USER_PWD_LOG_INFO.LOG_ID IS '主键ID';
COMMENT ON COLUMN SYS_USER_PWD_LOG_INFO.LOGIN_NAME IS '登录名';
COMMENT ON COLUMN SYS_USER_PWD_LOG_INFO.LOGIN_PWD IS '密码';
COMMENT ON COLUMN SYS_USER_PWD_LOG_INFO.CREATE_TIME IS '创建时间';
COMMENT ON TABLE SYS_USER_PWD_LOG_INFO IS '用户密码历史表';